### PR TITLE
Upgrading to Rails 5.2.3

### LINKED ISSUE #600: Upgrade from Rails 4.2.8 to Rails 5.0.1
Follow the steps below will definitely help:
https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-4-2-to-rails-5-0
This depends on #481 and #594

### PR DESCRIPTION
**Pull request by alaxalves**
Fixes #600 #752 #703 #425 #510 #533 #732  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/mapknitter-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by alaxalves** [comment]
Rails successfully worked at: https://jenkins.laboratoriopublico.org/job/Mapknitter-Unstable/192/console. Just pushed to unstable and it's fully operating.

**Comment by kaustubh-nair** [comment]
Awesome :balloon:

**Comment by kaustubh-nair** [comment]
I see a lot of errors for yarn
Can this be ignored?

**Comment by alaxalves** [comment]
> I see a lot of errors for yarn
> Can this be ignored?

Yes, the warnings and errors come from outside dependencies, and some of them we do not have control of

**Comment by jywarren** [comment]
Wow, very cool! Yarn is a bit chatty, indeed. Has this been reviewed elsewhere, and is there a "catch bugs in Rails 5" issue open? Just want to be completely ready before merging this and know where people are on it. Thanks so much!

**Comment by jywarren** [comment]
Also - the drop in coverage for map.rb - is that real, or related to the mis-tracking of coverage we've been seeing? Thanks!

**Comment by kaustubh-nair** [comment]
Why do we have so many pull requests?
We can just merge `development` to `main`

**Comment by alaxalves** [comment]
> Why do we have so many pull requests?
> We can just merge `development` to `main`

This MR is regarding merging Rails 5 into main. The `development` branch merge is regarding our entire work to `main`, not only Rails 5. Also the `development` branch mergeis for make easier to track our changes to `main`.

**Comment by jywarren** [comment]
Hi all, can you reply to my comments above just so we're all on the same page and ready for this? After resolving https://github.com/publiclab/mapknitter/issues/921 we should aim to merge this as soon as we can!

**Comment by kaustubh-nair** [comment]
Hi @jywarren Sorry I must have missed your earlier comment
Rails 5 is fully ready, there have been tiny issues popping up while trying to keep up with main, but we've fixed all of those. It's pretty much stable now. I've been wanting to test this on `unstable` but I think there is some issue with it?
Also, I've set up system tests here #936 and I think we can merge that together?
Thanks!

**Comment by jywarren** [comment]
Ah, there's one more conflict, can you resolve it? Can you point me and @icarito at any docs on the unstable issue? If we don't manage to get it running in time, we can merge this and resolve final issues on stable, although that's not best practice. Thank you! As soon as this is conflict-free, I'm +1 on merging it!

**Comment by alaxalves** [comment]
> Ah, there's one more conflict, can you resolve it? Can you point me and @icarito at any docs on the unstable issue? If we don't manage to get it running in time, we can merge this and resolve final issues on stable, although that's not best practice. Thank you! As soon as this is conflict-free, I'm +1 on merging it!

Just did it, took me a little while than expected since I realized that the Maps where not loading since we done a lot of merging

**Comment by jywarren** [comment]
Very exciting! Fingers 🤞

**Comment by alaxalves** [comment]
> Very exciting! Fingers

BTW, could u give me your input [here](https://github.com/publiclab/mapknitter/pull/824#issuecomment-520400711) too @jywarren

**Comment by jywarren** [comment]
Merged Rails 5!!!! 🎉 🎉 @publiclab/mapknitter-reviewers

**Comment by gauravano** [comment]
Great work and collaboration @alaxalves @kaustubh-nair @sashadev-sky 🎉 💯

**Comment by gauravano** [comment]
Hi, I was going through the recent codebase changes. I see schema.rb and schema.rb.example. I think, we should only keep one? 

What do you say?

**Comment by alaxalves** [comment]
> Hi, I was going through the recent codebase changes. I see schema.rb and schema.rb.example. I think, we should only keep one?
> 
> What do you say?

Yes, I we should only keep `schema.rb.example`, `schema.rb` should be removed and get into the `.gitignore`.

**Pull request merged**
