### PR TITLE
Update Contributing.md syntax mistake

### LINKED ISSUE #528: Contributing.md syntax mistake
File here: https://github.com/publiclab/mapknitter/blob/main/CONTRIBUTING.md

Formatting issue: two ## from markdown syntax left behind

### PR DESCRIPTION
**Pull request by sashadev-sky**
Fixes #528  (<=== Add issue number here)

See file here for easy reference: https://github.com/publiclab/mapknitter/blob/main/CONTRIBUTING.md

Saw a formatting issue where markdown ## syntax was left behind and decided to fix up the rest of the file too.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@icarito I am getting a key-server error and so is the last PR so there might be a problem with it again! Any updates on this? 

I made the PR by editing the file in the browser directly that doesn't make a difference right?

**Comment by icarito** [comment]
This shouldn't have failed - I restarted the build and will look at more options.

**Comment by icarito** [comment]
I just pushed a change to the High Availibility keyserver pool hopefully it'll make a difference!

**Comment by icarito** [comment]
The High Availibility pool also responded unreliably. I'll look at what else can be done.

**Comment by sashadev-sky** [comment]
@icarito Thank you!

**Comment by icarito** [comment]
I merged yet another change of keyserver, this time to the "IPV4 pool" as I read our errors were caused by IPV6. Hopefully it'll be reliable now!

**Comment by sashadev-sky** [comment]
@icarito it worked! Thank you!! @jywarren this one is ready for merge I don't think it needs a call to reviewers

**Comment by gauravano** [comment]
Merged :balloon: :tada: :+1:

**Pull request merged**
