### PR TITLE
Travis yml

### PR DESCRIPTION
**Pull request by jywarren**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- `rake test`
* [x] code has been rebased on top of latest master (check if another pull request was added recently, and please rebase)
* [x] pull request is descriptively named and, if possible, multiple commits squashed if they're smaller changes

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
@icarito - i'm trying to finish up the continuous integration here, and saw:

> ERROR: build path /home/travis/build/publiclab/mapknitter/mapknitter either does not exist, is not accessible, or is not a valid URL.

I made a couple changes in f5e71a7 and e5e86c7, which got it running, but I'm not sure it'll run on our actual server. Can you take a look and confirm?

Also, I got it almost all the way passing tests here, but finally see:

> Could not find rake-10.5.0 in any of the sources

However, it clearly shows rake 10.5.0 is installed higher up; and I wasn't able to find any difference from the sequence in plots2:

https://travis-ci.org/publiclab/mapknitter/builds/192711318

Anyways, it looks very close here, and would be great to get tests passing here too. However I know there are other priorities, just taking good notes.

**Comment by icarito** [comment]
Sure Jeff - it does ring a bell as something fixed in plots container.

**Comment by icarito** [comment]
Hi Jeff, actually, the issue seems to be related to the `.bundle/config` file - I'll update this PR with removing this directory and see how it goes.

**Comment by icarito** [comment]
It looks like I can't add commit to this PR: "Add more commits by pushing to the travis-yml branch on jywarren/mapknitter.". I had to create a new PR #235 to test it out.

**Pull request merged**
