### PR TITLE
Force SSL

### PR DESCRIPTION
**Pull request by icarito**
Fixes https://github.com/steviepubliclab/web/issues/279

I thought could would be needed but rails seems to have a setting for this.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [X] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [X] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation

### CODE REVIEW

**Comment by icarito** [comment]
We currently redirect like we used to, with NGINX in staging. I will disable this redirection to test the rails way, which we need in production because we no longer have an NGINX reverse proxy.

**Comment by icarito** [comment]
Will retry the failed test. My test in `unstable` worked as expected, it redirected to HTTPS without help from NGINX.

**Comment by sagarpreet-chadha** [comment]
Do we redirect users to `https` from `http` automatically?

**Comment by icarito** [comment]
Currently we don't, we used to rely on NGINX but we don't anymore. So this is needed now. I believe Codecov is crazy, this should pass and be merged.

**Comment by icarito** [comment]
Will merge this to match what we have in production.

**Pull request merged**
