### PR TITLE
header search bar stays together

### LINKED ISSUE #508: Search bar must be present on a single line
### What happened just before the problem occurred
The search bar is not present on a single line.
Selection_126

It must be present in a single line. 

### Relevant URLs
https://mapknitter.org/

### PublicLab.org username
divyabaid16

(to help reproduce the issue)

### Browser, version, and operating system
Linux Mint

For bug reports, fill out the above template; for feature requests, you can delete the template.

### PR DESCRIPTION
**Pull request by sashadev-sky**
Fixes #508  (<=== Add issue number here) (originally discovered by @divyabaid16 for a different search bar but that one has since been removed)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sashadev-sky** [comment]
this PR ensures the search bar doesn't split from the search icon when the page becomes smaller (does not fix the issue of the header disappearing all together)
search-bar

for documentation, here is a **before** gif:

search-barbefore

**Comment by sashadev-sky** [comment]
@publiclab/reviewers

**Comment by gauravano** [comment]
Hi @sashadev-sky, changes look great. There's a conflict, please resolve that. Thanks!

**Comment by sashadev-sky** [comment]
@gauravano rebased and with the new color scheme there was also a noticable overlap between the search bar and the search icon so I added a 'margin-left: 2px' to the icon. This is the result now, feel free to merge if it checks out for you! 

Screen Shot 2019-05-26 at 7 22 17 PM

**Comment by sashadev-sky** [comment]
@gauravano @jywarren I rebased and fixed the travis issues, can we merge this :)

**Comment by jywarren** [comment]
Oh this looks really nice. Thanks @sashadev-sky !!!

**Pull request merged**
