### PR TITLE
Ruby upgrade to 2.4.4

### LINKED ISSUE #319: Ruby version update
Hi, we are using very old ruby version `2.1.2` which is troubling with the installation. 

Errors I faced:
1. Error running '__rvm_make -j8' while installing ruby 2.1.2

Solved by `rvm get head`
After completing installation of ruby version, I switched to it.

2. I ran `bundle install` and got below error

```
ZenTest-4.11.1 requires rubygems version < 3.0, which is incompatible with the
current version, 3.0.2
```

I deleted the Gemfile.lock and ran bundle install again.

3. After that I got this error in bundle install 

```
Gem::RuntimeRequirementNotMetError: nokogiri requires Ruby version >= 2.3.0. The
current ruby version is 2.1.2.95.
An error occurred while installing nokogiri (1.10.1), and Bundler
cannot continue.
Make sure that `gem install nokogiri -v '1.10.1' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  aws-sdk was resolved to 1.5.8, which depends on
    nokogiri
```

Many new user would be going through the same situation if they try to switch from plots2 to mapknitter and without using too because our dependencies are old and conflicting. 

@jywarren should we update ruby version and important gems first to make installation easier for contributors? Thanks!

### PR DESCRIPTION
**Pull request by gauravano**
Fixes #319 

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code has been rebased on top of latest master (check if another pull request was added recently, and please rebase)
* [x] pull request is descriptively named and, if possible, multiple commits squashed if they're smaller changes

Thanks!

### CODE REVIEW

**Comment by gauravano** [comment]
Hi @icarito @jywarren , can you please help in completing this upgrade? Also, I think we should upgrade to ruby 2.4.4 so contributors will not face any issue while switching from plots2 to mapknitter. 

Thanks!

**Comment by gauravano** [comment]
Hi @icarito @jywarren , can you please help in completing this upgrade? Also, I think we should upgrade to ruby 2.4.4 so contributors will not face any issue while switching from plots2 to mapknitter. 

Thanks!

**Comment by jywarren** [comment]
Hmm, modeling on https://github.com/publiclab/plots2/blob/master/Dockerfile...

**Comment by jywarren** [comment]
Hmm... /bin/sh: 1: npm: not found

**Comment by jywarren** [comment]
Aha! Running :-)

```
Error: test_should_get_profile(UsersControllerTest): TypeError: ActiveSupport::Duration can't be coerced into Integer
```

Could do with the fixtures timestamp attributes. We should check how they're generated in plots2, say in the User model.

**Comment by jywarren** [comment]
https://stackoverflow.com/questions/42083737/gem-load-error-is-activesupportduration-cant-be-coerced-into-integer -- ok, can we try running this locally and see what exact line this happens on?

**Comment by jywarren** [comment]
Maybe @Souravirus has an insight, too? He's done a lot of such upgrades :-)

**Comment by sashadev-sky** [comment]
@jywarren @gauravano I was doing some research for another issue I am opening right now and I just stumbled on this on the [MySQL site](https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-data-dictionary-changes):

"Removal of MAXDB means that the TIMESTAMP data type for CREATE TABLE or ALTER TABLE is no longer treated as DATETIME."

I think this could be the cause? I will not be able to check until for sure later tonight but I hope its helpful! 

When I run `rake test` this test fails as an ActiveRecord Error: 
```
test_should_get_profile(UsersControllerTest): ActiveRecord::StatementInvalid: Mysql2::Error: Incorrect datetime value: '2019-02-07 12:10:44 UTC' for column 'remember_token_expires_at'
```

**Comment by jywarren** [comment]
oh cool - is that the only one that fails or is that just representative?
We should check where we may be actually setting that value and see if we
need to add or remove some kind of formatting at the moment of insertion.
Thanks!

**Comment by sashadev-sky** [comment]
there are a few small formatting issues. I updated them and will make pull request shortly 👍

**Comment by jywarren** [comment]
@sashadev-sky once we merge #323, do you think this will work once rebased?

**Comment by sashadev-sky** [comment]
@jywarren I updated my local repo to use ruby 2.4.4 and ran the tests and I am now getting those errors. So I guess that was not the fix. But since I have it locally setup already I will see if I can try to fix that as well, change my ruby v back to 2.1.1, make sure everything still works then push another commit onto my current PR?

**Comment by sashadev-sky** [comment]
@jywarren the issue was because Rails 3.2 and Ruby 2.4 are not compatible and lies in the ActiveSupport library. This incompatibility was fixed in a later versions of Rails. 

I don't know if there is interest in updating the Rails version as well, but in the meantime, I added two more files in config/initializers and there are no more errors. I just pushed them to my PR #323 and will make another commit with notes added to them shortly. @gauravano 

- ActiveSupport::Duration fix: [see here](https://stackoverflow.com/questions/41703128/error-while-trying-to-load-the-gem-devise-activesupport-duration-cant-be-coe)
- Arel::Visitor fix: [see here](https://stackoverflow.com/questions/44053672/simple-rails-app-error-cannot-visit-integer)

**Comment by Souravirus** [comment]
Hi @jywarren @gauravano and @sashadev-sky, I am ready to help in every possible way. Just ping me I will be available.
Thank you !!

**Comment by jywarren** [comment]
Definitely we'll be updating Rails -- see #305 -- but is there an intermediate version of Ruby we could upgrade to in the meantime or should we hold off until we upgrade Rails? 

THANK YOU for this great investigative work, @sashadev-sky !

**Comment by sashadev-sky** [comment]
@jywarren With the customizations I made I think I bridged most of the gap between Ruby 2.4.4 and our current version of Rails so that it works as expected. So I think it is safe to run that update whenever and then the customizations can just be removed once Rails 5 is implemented without any effect on surrounding code. I guess its like building a bridge to make it easier to cross if that makes sense.

**Comment by sashadev-sky** [comment]
Also, just wanted to share I think the [source code for ActiveRecord](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/attribute_methods.rb#L221) is a great resource for pinpointing errors whenever you upgrade a version. And all the code is right there for you to customize for compatibility in a project. It's also just really cool to look at it and see how Rails works. But yeah, just because we can customize doesn't mean we should, upgrading is ultimately the solution. Customizing can be used in interim of upgrades to get your code in shape and make transitioning smooth.
Sorry for the rant!!

**Comment by jywarren** [comment]
+1 this is awesome Sasha, thanks. My notes on your code in the other PR
focus on this idea of "knowing when to remove the customizations later" --
we have the occasional messy code segment in plots2 for example where it's
not clear when we ought to cut it out again. So yeah, let's clearly comment
and then we can move forward!

**Comment by sashadev-sky** [comment]
@jywarren Yes will do that today! I am just doing a little research to make sure I know / document all the ways it can effect our database

**Comment by jywarren** [comment]
yeah awesome!!!

**Comment by sashadev-sky** [comment]
@gauravano @jywarren what is the status on this update? I was thinking to open a PR to update mySQL after it

**Comment by gauravano** [comment]
hey @sashadev-sky, I will trigger the build again. Let's see how it goes now.

**Comment by gauravano** [comment]
@jywarren @sashadev-sky try this branch locally and please review this PR. Thanks!

**Comment by sashadev-sky** [comment]
@gauravano I will check this out today thank you :)

**Comment by sashadev-sky** [comment]
@gauravano I ran your PR locally and this worked for me! 👍

Just one thing to maybe add, even though it is not specifically Ruby it doesn't seem like it needs its own PR:
[mapknitter/config/initializers/new_rails_defaults.rb](https://github.com/publiclab/mapknitter/blob/main/config/initializers/new_rails_defaults.rb)

this file says it could have been removed a while ago (with Rails 3). I commented it out and there was no difference in setup for me. Should we comment it out and change the file name to maybe `old_rails_defaults.rb`?

**Comment by sashadev-sky** [comment]
@gauravano @jywarren @Souravirus I will be opening an issue to update mySQL next. I have gauravano's PR here to guide me but is there any specific documentation that I should be following?

**Comment by jywarren** [comment]
This seems super, and if you want to merge after removing [mapknitter/config/initializers/new_rails_defaults.rb](https://github.com/publiclab/mapknitter/blob/main/config/initializers/new_rails_defaults.rb) i'd be fine with that!

**Comment by sashadev-sky** [comment]
@jywarren what is the process for merging? Do you just click "Squash and merge" in this case and your good to go?

**Comment by jywarren** [comment]
Yes, that's right!

**Comment by jywarren** [comment]
I went ahead and merged this but @sashadev-sky if you want to remove that file in a new PR, that'd be great!

**Comment by jywarren** [comment]
Thanks both of you, this is great.

**Comment by sashadev-sky** [comment]
@jywarren I’ll go ahead and do that for the mySQL update

Sasha Boginsky
Goizueta Business School
Emory University | BBA Class of 2017
646.241.5756 | sasha.boginsky@emory.edu

**Pull request merged**
