### PR TITLE
Gallery page and front-page mobile responsive

### PR DESCRIPTION
**Pull request by cesswairimu**
Fixes 

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/mapknitter-reviewers` for help, in a comment below

### CODE REVIEW

**Comment by cesswairimu** [comment]
Mobile view front-page
---------------------------------

screencapture-localhost-3000-front-page-2019-06-28-01_12_08



Gallery page
---------------------
screencapture-localhost-3000-gallery-2019-06-28-04_50_14


Authors Tab
--------------------
screencapture-localhost-3000-gallery-2019-06-28-04_50_28

**Comment by jywarren** [comment]
This looks great! Ready to merge?

**Comment by cesswairimu** [comment]
Yeah its ready

**Comment by jywarren** [comment]
Awesome! Let's see it build on stable!

**Pull request merged**
