### PR TITLE
Bump leaflet full hash

### PR DESCRIPTION
**Pull request by rarrunategu1**
Fixes #731  (<=== Add issue number here)

@publiclab/reviewers Please review for merge per approvals on issue #731  by @sagarpreet-chadha and @sashadev-sky 

[//]: # (To mark checkbox write 'x' within the square brackets)

* [X] PR is descriptively titled 📑 and links the original issue above 🔗
* [X] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [X] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/mapknitter-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by rarrunategu1** [comment]
@jywarren @gauravano I noticed when doing the pull request it added all of these commits but only the two files that I changed for the update on leaflet-fullhash are listed as changed files.  Am I doing something wrong when doing these pull requests?

**Comment by jywarren** [comment]
Ah, i see - yes, it's from all the merge commits, but GitHub can see that they didn't affect the final diff of your whole PR. If you want to get rid of them, you can rebase your PR branch over the latest main branch!

**Comment by jywarren** [comment]
But, they will get squashed when we merge in any case. Thanks!

**Comment by jywarren** [comment]
Should this be good to go? I clicked `Resolve conflicts`. Thanks!

**Comment by jywarren** [comment]
Oh wait, I'll let you resolve the conflicts here. Thanks!

**Comment by rarrunategu1** [comment]
@jywarren I resolved the conflict.  It just has to finish building, which should come out fine and then it's ready to merge.  I'll check in a little while to make sure Travis build succeeded.

**Comment by jywarren** [comment]
Great, thanks!!

**Pull request merged**
