### PR TITLE
Turn off project, turn on patch for codecov

### LINKED ISSUE #810: inconsistencies with CodeCov rejections
Possibly in relation to #747, I'm seeing that some PRs are blocked if they have no tests, which is fine, but that when adding tests, 

1. we can't seem to get the Codecov reported coverage for the PR to change
2. CodeCov's info seems inconsistent; initially this PR (https://github.com/publiclab/mapknitter/pull/801) reflected a drop in coverage to the sessions controller,in CodeCov's comment. But after rebasing, now it shows a drop in the Annotations controller:

image

Why might CodeCov be varying in its reporting? cc @kaustubh-nair 

Thank you!

### PR DESCRIPTION
**Pull request by kaustubh-nair**
Might fix #810 
The inconsistency is arising from project. Let's try this and see if it fixes the codecov issue

### CODE REVIEW

**Comment by kaustubh-nair** [comment]
@jywarren let's merge this and see what happens

**Comment by kaustubh-nair** [comment]
Coverage decreased again?!
why!?

**Comment by kaustubh-nair** [comment]
Coverage decreased again?!
WHY !? :confused:

**Comment by kaustubh-nair** [comment]
I just realized that turning `project` or `patch` off won't make a difference. There's something wrong with the coverage reporter itself

**Comment by jywarren** [comment]
OK! Thanks!

**Comment by jywarren** [comment]
Oh no! Was I not supposed to? Shall we revert? We may need to open another PR. But at least we're no worse off than we were. Thanks @kaustubh-nair I'm sure we'll figure it out! ❤️

**Comment by kaustubh-nair** [comment]
Yeah this doesn't fix it
It's okay though, I'll open a new PR

**Pull request merged**
