### PR TITLE
added 'Ask a question' button

### PR DESCRIPTION
**Pull request by edsonmendieta**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ I'm not sure what this is.] tests pass -- `rake test`
* [ I believe so...?] code has been rebased on top of latest master (check if another pull request was added recently, and please rebase)
* [I believe so. ] pull request is descriptively named and, if possible, multiple commits squashed if they're smaller changes

Thanks!

### CODE REVIEW

**Comment by edsonmendieta** [comment]
I clicked on "View changes", edited the file there, and then committed to my 'patch-1' branch. 

Is that the proper way to go about it, or am I supposed to create an entirely new pull request?

**Comment by jywarren** [comment]
Hi -- this looks perfect; merging now. If you're looking for a new challenge, please take a look at our `help-wanted` list: https://github.com/publiclab/plots2/labels/help-wanted

Thanks!

**Comment by jywarren** [comment]
And it's now live!

screenshot 2016-12-12 at 9 19 38 pm

**Comment by edsonmendieta** [comment]
So cool! 

Thanks for your help throughout this!

**Comment by ebarry** [comment]
Thanks @edsonmendieta !!!!! this is super helpful to connect folks using mapknitter.org to the main public lab Question and Answer feature. We really appreciate your work on this!

**Pull request merged**
