### PR TITLE
Upgrade app to Bootstrap 4

### LINKED ISSUE #377: Update Bootstrap version to the latest version
The project is currently using Bootstrap 3.2.0, but it would be nice to update it to the newest version (now it`s at 4.3.1).

I'm finishing some tweaks on the navbar but as soon as it's finished I can start working on this one, but feel free to suggest anything or even start working on it :)

### PR DESCRIPTION
**Pull request by stefannibrasil**
Fixes  #377 

(sorry for the confusion, but I had a confusion with my upstream repo, so I moved everything to this new branch).
Hi all, I have some questions/notes:

- Why do we have two `bower.json` files? I wasn't sure which one to use, so I updated both of them;
- In order to make Bootstrap 4 work, I had to install the `popper_js` gem and update `jquery-ui` version;

A little more about this PR: I just updated some of the components that were broken from switching to Bootstrap 4, especially because we will soon update the UI.

Please let me know if I did those version updates correctly, this was my first time doing something like this! :)
Appreciate any help here, I think I didn't forget anything here :shipit:

### CODE REVIEW

**Comment by stefannibrasil** [comment]
@icarito @jywarren this is the most updated branch. I just don't know how to use the staging server yet. Thanks in advance!

**Comment by icarito** [comment]
Hi @stefannibrasil I apologize I had promised to document the staging instance but I ran into troubles when I copied the production data into the staging database it's not starting correctly looks like some kind of version incompatibility that I monkey-patched here https://github.com/publiclab/mapknitter/blob/main/Dockerfile#L37 in order to get us into Debian 10 cycle to use GDAL. I'll fix it tonight and ping you!

**Comment by stefannibrasil** [comment]
@icarito don't worry, no need to apologize, take your time! I'll record a video with the changes in the meantime. Thanks!!

**Comment by jywarren** [comment]
I just reviewed the video and this is great. Once we get staging up, let's use https://lookback.io to get people's reviews on it before rolling it out? Thanks Stefanni!!!!!

**Comment by icarito** [comment]
Hi here's a short paragraph on how to use the `unstable` instance, basically like we use the same for `plots`.

**Comment by icarito** [comment]
@jywarren if you are ok to merge #462 and probably #489 then this should work for staging both **main** and **unstable** branch.

**Pull request merged**
