### PR TITLE
Add environment variables for RECAPTCHA

### PR DESCRIPTION
**Pull request by icarito**
Fixes deployment issue with not finding this value.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/mapknitter-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by icarito** [comment]
I believe this should be merge, although, by itself, it did not fix the issue. We're still seing `undefined method `recaptcha_tags'` on this route. I'll check the gemfile...?

**Comment by jywarren** [comment]
What if it's related somehow to this long discussion? https://github.com/publiclab/mapknitter/issues/953#issuecomment-523473479

**Comment by icarito** [comment]
> What if it's related somehow to this long discussion? [#953 (comment)](https://github.com/publiclab/mapknitter/issues/953#issuecomment-523473479)

No I don't think so, this time recaptcha.rb has the correct initialization lines...

**Comment by icarito** [comment]
I'm going to merge this as I need to deploy a new version with new robots.txt

**Pull request merged**
