### PR TITLE
FIX: Squished cancel export button with a progress bar

### PR DESCRIPTION
**Pull request by developer22-university**
Fixes (number of this issue -> #1193)
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/mapknitter-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by VladimirMikulic** [comment]
@developer22-university could you rebase this push only the change that you made?
1) Check out your patch branch(`developer22-university-patch-1`)
2) Run git rebase master
3) git push -f

Thanks.

**Comment by developer22-university** [comment]
@VladimirMikulic  @SidharthBansal 
please help in installation of redis server in ubuntu for windows


Screenshot (62)

**Comment by developer22-university** [comment]
i installed redis , and server following
https://github.com/publiclab/plots2

**Comment by developer22-university** [comment]
@VladimirMikulic

**Comment by VladimirMikulic** [comment]
@developer22-university I am glad that you were able to set up a repo. On the other hand, this PR is no longer needed because the issue has been resolved by another user.

Thanks for your work and I hope that you learned something new :tada:

**Pull request closed without merging**
