### PR TITLE
Backend search constraints (length & whitespace)

### PR DESCRIPTION
**Pull request by sashadev-sky**
References #https://github.com/publiclab/mapknitter/issues/520#issuecomment-482941133 (<=== Add issue number here)

Note there is a PR open for this but that implementation was not working as expected originally and is also stale now so going to try to just solve the problem myself and close that one

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@publiclab/reviewers

**Comment by sashadev-sky** [comment]
@gauravano I was going to do this in a follow-up PR - got a little lazy here. It's not that much work so I will just implement it here and mention you for another review. Otherwise this should have been an FTO so I feel bad

**Comment by gauravano** [comment]
No issues. Let me know, whenever you're done. Thank you!

**Comment by sashadev-sky** [comment]
@gauravano ok this is ready. this is a backend implementation that imposes a 3 character limit, not including spaces. So it allows the person to type spaces and submit them and it trims left and right whitespace and extra white space between words so you can search for a map named "new york" like 
<pre>"  new     york    "</pre> and itll still find it. 

But it doesn't include spaces in the character count so if you tried to search `"nn        "` it would impose the character count on you. 

Also does not allow for blank search. 

Any further restrictions should be a follow up on the front-end.  

I also did a lot of refactoring of `map.rb` but the main driver behind this code is in the search action in maps controller

let me know if its good to go! Thanks :)

**Comment by jywarren** [comment]
Oops, i merged your header fix and now I think it created a conflict here! Sorry!

**Comment by sashadev-sky** [comment]
@jywarren rebased!

**Comment by jywarren** [comment]
Super!!!

**Pull request merged**
