### PR TITLE
Add a default bands_strings text

### LINKED ISSUE #920: Add a default text for `bands_string` in exports table
A more maintainable way we should fix this is in the DB directly and update the default value for the bands_string. Otherwise future code will easily hit this error again. 
```
class AddExportTypeBands < ActiveRecord::Migration
  def self.up
    add_column :exports, :bands_string, :text, :default => "", :null => false
    add_column :exports, :export_type, :string, :default => "normal", :null => false
  end

  def self.down
    remove_column :exports, :bands_string
    remove_column :exports, :export_type
  end
end
```
but for some reason, it's not there. default => "normal", however, is there.

since we've externalized the export data, I know a lot of these columns will be deprecated. is bands_string one of them? What is bands_string even storing? Do we need this column because best would be removing it if we don't
_Originally posted by @sashadev-sky in 
https://github.com/publiclab/mapknitter/pull/913#pullrequestreview-272920627_

A follow-up to #912

### PR DESCRIPTION
**Pull request by cesswairimu**
Fixes #920 

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/mapknitter-reviewers` for help, in a comment below

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@cesswairimu just made a big db schema update in #959 that maybe will be merged. For this one, I was thinking to just delete the bands_string column. I think it is not being used for anything. But I haven't confirmed that 100%. What do you think?

**Comment by cesswairimu** [comment]
Sounds good...Thanks so much @sashadev-sky :+1: . Closing this

**Comment by cesswairimu** [comment]
Actually I will just remove the column code and push the changes to this branch. I am very quite familiar with the export aspect. But I have searched the code base and we don't use it anywhere...pinging @jywarren to confirm if its safe to remove that column. Thanks again.

**Comment by sashadev-sky** [comment]
thank you!

**Comment by cesswairimu** [comment]
Closing this the bug hasn't come up. Seems like this won't be necessary

**Pull request closed without merging**
