### PR TITLE
Add border to Authors in gallery template #965

### PR DESCRIPTION
**Pull request by nickycutesc**
First Timers is awesome! Added a border for issue #965

Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/mapknitter-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sirnickyc** [comment]
thanks @divyabaid16 ! So excited that I was able to do this. Attached is the screenshot.

IMG_2862

**Comment by divyabaid16** [comment]
Oh!! Actually, I meant you to upload the screenshot of the change that code corresponds to @sirnickyc

**Comment by divyabaid16** [comment]
Do you need any help @nickycutesc ?
Thanks!

**Comment by nickycutesc** [comment]
Hey Divya,

Sorry about the late response! So what would the screenshot entail? Do you have any sample screenshots for earlier issues that I can reference?

Thanks,
Nick

**Comment by divyabaid16** [comment]
@nickycutesc The screenshot should show how the UI should look after you have made the changes.

**Comment by nickycutesc** [comment]
So I would need to download the application in order to show this screenshot, correct?

**Comment by divyabaid16** [comment]
Yes!!

**Comment by nickycutesc** [comment]
Ok, great I'll get to that later in the week.

**Comment by divyabaid16** [comment]
Okay, that's great @nickycutesc !

**Comment by VladimirMikulic** [comment]
@divyabaid16 here is the screenshot:

Screenshot_20200110_042910

**Comment by divyabaid16** [comment]
Okay, great.

**Comment by jywarren** [comment]
Awesome, thank you!!!

**Comment by nickycutesc** [comment]
Hey FirstTimers, thanks so much for this opportunity and for the invitation to PublicLab! My Twitter handle is: nickycutesc.

**Pull request merged**
