### PR TITLE
Update README.md MapKnitter Spelling

### LINKED ISSUE #676: README Update Mapknitter spelling
### What happened just before the problem occurred

We have at least 4 different names for mapknitter in the README:

- MapKnitter 2

- MapKnitter

- Mapknitter

- Map Knitter (This one is in the license!)

Can we standardize to one name? I think Mapknitter is sensible?

### PR DESCRIPTION
**Pull request by sashadev-sky**
Fixes #676  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@jywarren @gauravano need at least one approval to merge this!

**Comment by sashadev-sky** [comment]
@publiclab/mapknitter-reviewers

**Comment by sashadev-sky** [comment]
@jywarren was about to merge but just noticed one additional thing: The header for plots2 is currently "PublicLab.org" instead of "plots2". Did you want the same thing here? I think it looks good in plots2, although I am not sure how I feel about the snake case usage so up to you!

**Comment by jywarren** [comment]
I had it PublicLab.org because not everyone immediately realizes that it's
the same thing... or knows what plots2 is!

**Comment by sashadev-sky** [comment]
@jywarren took me a bit to figure that out myself 😸 Ok I will rebase this and merge right now!

**Pull request merged**
