### PR TITLE
improve setting dropdown

### PR DESCRIPTION
**Pull request by avsingh999**
References #387 (\<=== Add issue number here)

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code has been rebased on top of latest master (check if another pull request was added recently, and please rebase)
* [x] pull request is descriptively named and, if possible, multiple commits squashed if they're smaller changes

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
This looks great! Can you show a screenshot please so we can confirm? Thanks so much!!!

**Comment by avsingh999** [comment]
@jywarren  I have removed this setting for anonymous. And only showing when user login.
**With anonymous**
pub8

**with login**
pub9

**Comment by avsingh999** [comment]
@jywarren @SidharthBansal please review
thanks : )

**Comment by jywarren** [comment]
Oh, did you close this by accident? Thanks!

**Comment by avsingh999** [comment]
@jywarren Sorry I don't know what happen with this but someone sent pr.
thank you : )

**Pull request closed without merging**
