### PR TITLE
Add noopner for target=_blank

### LINKED ISSUE #582: target=_blank not protected by noopener
### Relevant URLs

https://

https://github.com/publiclab/mapknitter/blob/8ed7283b845dbce1a932d9abd3cba226fec2400f/app/views/layouts/_header.html.erb#L20-L26

### PublicLab.org username

(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

### PR DESCRIPTION
**Pull request by sashadev-sky**
Fixes #582 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@publiclab/reviewers is this still a valid security concern?

**Comment by jywarren** [comment]
Based on https://mathiasbynens.github.io/rel-noopener/, i thought this was important for links that people put into our site, but not necessarily for ones that we ourselves put in? But I may not fully grasp the security implications. Would this be something to insert into, say, comment text or map description text?

**Comment by sashadev-sky** [comment]
@jywarren I actually used the same site when I was looking it up.. but I'm thinking what you're saying makes sense. Like if we are redirecting to another PL page, then there's no security hole to get control of the window object because its our code not foreign code.

**Comment by sashadev-sky** [comment]
@jywarren are you thinking to just close this then?

**Comment by jywarren** [comment]
Yeah makes sense. It's something to watch for in user-submitted data though, thank you!

**Pull request closed without merging**
