### PR TITLE
All layers from leaflet-environmental-layers library added .

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
Continued #268 !

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code has been rebased on top of latest master (check if another pull request was added recently, and please rebase)
* [x] pull request is descriptively named and, if possible, multiple commits squashed if they're smaller changes

Thanks!

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
Hi !
I am facing problem in 1 layer which is PurpleAir Layer Library because the dependency Leaflet-heatmap is not on bower .

- Added all other layers 👍 🗺 . 

- Leaflet-hash also added .

screen shot 2018-07-19 at 10 49 39 pm


How does this looook ?

**Comment by jywarren** [comment]
Looks awesome! You can also refer to a github repository directly from Bower, as long as it has a "release" - https://github.com/publiclab/plots2/blob/master/bower.json#L7

**Comment by jywarren** [comment]
Did you try the bower trick? Ready to merge this as soon as you are! Thanks!

**Comment by sagarpreet-chadha** [comment]
Hi...lets merge this and for the 1 remaining layer i will open another PR 😄 . Thanks !

**Comment by jywarren** [comment]
Fantastic!!

**Pull request merged**
