### PR TITLE
Style updates for about page and footer

### LINKED ISSUE #1113: Redesign UI for about page
We moved a couple things around on the about page. This is how it  looks like, currently

screencapture-localhost-3000-about-2019-11-10-22_49_39

 There are a few improvements that could be done to it. Suggestions...
- [ ] The image is so stretched out(could use some styling or maybe we get another image? Is the positioning right?
- [ ] We could add some more content on the about page and maybe some links to the wiki on how mapknitter was used
- [ ] We could add more helpful statistics on the the statistics section..maybe how many maps we have in total and images?

-----------------------------------------
Suggestions are definitely welcome..feel free to edit/comment below. Thanks

### PR DESCRIPTION
**Pull request by Uzay-G**
Fixes #1113
@cesswairimu @publiclab/mapknitter-reviewers 

I got a bit creative and made a few changes to the style of the mapknitter footer and about section.
The about page in this branch has changed from the one on the [mapknitter website](https://mapknitter.org)
to this:

about-map1
about-map2
about-map3

And the footer will have gone from this:
before-footer

to this:
after-footer

I'd really appreciate your feedback about these changes and am very open to suggestions and more ideas I could add onto the project.

Edit: I had a question, is the ```Warpable``` model in the code the images. If not, what are some ways I could count the number of images uploaded?

Is there a way to preview these changes for you guys before we merge? That way you could see the changes and how they look.

Thanks!

### CODE REVIEW

**Comment by Uzay-G** [comment]
Could someone explain the codecov report and why it is failing?

**Comment by cesswairimu** [comment]
Wow this looks really great :tada: :tada: I love the last new images really creative love it :heart: ....I didn't realize the icons would change too much..lets hear the opinion from others @publiclab/mapknitter-reviewers, kindly let me know what you think about the social media icons.

**Comment by Uzay-G** [comment]
@cesswairimu Thank you so much! Yeah I totally get it for the icons just wanted to see what it could look like. I understand if it's a bit too bold :smile:.

**Comment by cesswairimu** [comment]
The codecov is complaining about test coverage...It expects to have some tests added but I don't see any reason to add tests as all u did is mostly front-end stuff.

**Comment by cesswairimu** [comment]
welcome to mapknitter @Uzay-G :smile:

**Comment by tsparksh** [comment]
Hey @Uzay-G, can you check what happened to your changes, please? Now the footer looks like this
image

**Comment by Uzay-G** [comment]
Thanks I'll fix it.

**Pull request merged**
