### PR TITLE
Remove legacy image controller code #404

### LINKED ISSUE #404: Remove legacy image controller code
This issue is reserved for applicants to [Public Lab’s Providence code fellowship](https://publiclab.org/pvd). Please feel free to help applicants, but if you are looking for a first-timers-issue of your own and are not applying for the position, please see our coding Welcome Page at https://code.publiclab.org. 

Applicants - upon completion (when your pull request is merged), please include the link to this issue in your application at https://publiclab.org/pvd.

****

Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/controllers/images_controller.rb](https://github.com/publiclab/mapknitter/blob/main/app/controllers/images_controller.rb) in the `mapknitter` repository (press the little pen Icon) and edit the line as shown below. 

To get help installing the application on your computer, see [the project README](https://github.com/publiclab/mapknitter/tree/main/README.md) and get help at #307 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -9,22 +9,6 @@ class ImagesController < ApplicationController
   #Convert model to json without including root name. Eg. 'warpable'
   ActiveRecord::Base.include_root_in_json = false
 
-  # legacy
-  def new
-    @map = Map.find params[:id]
-    @warpable = Warpable.new
-    respond_to do |format|
-     format.html { render :template => 'legacy/new', :layout => false } 
-     format.json { render :json => @warpable }
-    end
-  end
-
-  # legacy
-  def uploaded_confirmation
-    @warpable = Warpable.find params[:id]
-    render :template => 'legacy/new', :layout => false
-  end
-
   # proxy, used if MapKnitter is being backed by Amazon S3 file storage, 
   # to enable client-side distortion using webgl-distort, which requires same-origin
   def fetch
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by milomacphail**
Deleted the lines from the selection indicated in the issue.

Fixes #404

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code has been rebased on top of latest master (check if another pull request was added recently, and please rebase)
* [x] pull request is descriptively named and, if possible, multiple commits squashed if they're smaller changes

Thanks!

### CODE REVIEW

**Comment by milomacphail** [comment]
Hi! I think this is all set. Can you please review?

Let me know if I'm missing anything. Thanks!

**Comment by jywarren** [comment]
Yes, this looks good; were you able to install the application locally as well? Thanks!!!

**Comment by jywarren** [comment]
Hi @milomacphail just checking if this went well? Thanks!

**Comment by milomacphail** [comment]
Hey Jeff! Yep I am all good over here. Thanks!

Anything else I can do?

**Comment by jywarren** [comment]
Nope, just checking - thank you very much!!!

**Pull request merged**
