### PR TITLE
change to featured mappers

### LINKED ISSUE #767: Optimization of front page
Hi @cesswairimu I realized that stable front page is quite slow and that it's most likely the listing of mappers. I think we need to make a cache around that -- at least for now, and then somehow optimize that query... It's really slow, and makes sense because it's counting all maps?

We can work on this on Monday!

### LINKED ISSUE #773: New default map tile layer
I'm working on this!

### PR DESCRIPTION
**Pull request by jywarren**
Addressing #774 and other front page fixes!

Fixes #767

Fixes #773

### CODE REVIEW

**Comment by jywarren** [comment]
I think this is ready... @cesswairimu can you test it out? It's not perfect but should be pretty good.

**Comment by cesswairimu** [comment]
Sure! pulling this

**Comment by jywarren** [comment]
Thanks! Just added another commit, sorry!

**Comment by cesswairimu** [comment]
no worries

**Comment by jywarren** [comment]
OK! I made another change - check it out, this is cool!

**Comment by jywarren** [comment]
Hmm, but why isn't it showing your current location?

**Comment by jywarren** [comment]
I think there are some timing issues with the browser geocoding versus the default locations...

**Comment by jywarren** [comment]
OK, everything seems to work /except/ if you block browser geocoding... it works if you then refresh the page, but not initially on clicking "block".

**Comment by cesswairimu** [comment]
Oh yeah I see...BUt its now super fast....on my end when I block then refresh it shows my location anyways without prompting

**Comment by jywarren** [comment]
but, are you sure, because I made Nairobi one of the featured locations - 😄 ?

**Comment by cesswairimu** [comment]
:laughing: my bad yeah I see

**Comment by jywarren** [comment]
OK, i think i got it! Had to initialize the map with a default location i guess.

**Comment by jywarren** [comment]
I think i'll merge this, sound good?

**Comment by cesswairimu** [comment]
Yeah, This is great!! :rocket: thanks

**Comment by jywarren** [comment]
OK, adding one more thing - a very brief "quick start" gif!

image

**Comment by jywarren** [comment]
One last change! 
image

**Comment by jywarren** [comment]
Noting that CodeCov will briefly flag dropped coverage but then corrects itself - nice work on getting the parallel task coverage reporting working! cc @kaustubh-nair @alaxalves 

image

**Comment by jywarren** [comment]
Building on stable now!

**Comment by jywarren** [comment]
cc @stefannibrasil @alaxalves @divyabaid16  @kaustubh-nair @rarrunategu1 @cesswairimu @sashadev-sky @publiclab/mapknitter-reviewers @icarito

**Comment by jywarren** [comment]
I'm seeing an error on stable... not sure why. Should check logs. https://jenkins.laboratoriopublico.org/job/Mapknitter-Stable/

Oh...

```
NameError: uninitialized constant Recaptcha::ClientHelper
/app/config/initializers/recaptcha.rb:4:in `<class:Base>'
/app/config/initializers/recaptcha.rb:3:in `<top (required)>'
```

Looking back to when this first happened...

**Comment by jywarren** [comment]
@kaustubh-nair @alaxalves i think it first failed in this PR merge, though not sure it's related: https://jenkins.laboratoriopublico.org/job/Mapknitter-Stable/168/

**Comment by jywarren** [comment]
#749

**Comment by jywarren** [comment]
It did change:

`recaptcha (4.14.0)	    recaptcha (5.0.0)`

**Comment by jywarren** [comment]
That change had originally been here, i think? https://github.com/publiclab/mapknitter/pull/671

**Comment by jywarren** [comment]
I'm going to try to revert that version change, to see if it'll build on `stable`

**Comment by jywarren** [comment]
OK, reverted it in d5a4676cb5445cd539e1c8dff7beee588371b44d

**Comment by jywarren** [comment]
Oof, ok it built, but now I'm seeing a 404 error for the front page!

**Comment by jywarren** [comment]
OK, i think i solved this too. Pushed and rebuilding... 5dc6d7a

**Comment by jywarren** [comment]
Solved! Apologies for the commits to main. We're all good now @publiclab/mapknitter-reviewers and stable site is loading properly!

**Pull request merged**
