### PR TITLE
Display images on home page

### LINKED ISSUE #570: Do not show anonymous images on home page.
### What happened just before the problem occurred
Add an option to view anonymous posts by clicking on anonymous posts.
Show only registered user posts on home screen.

### Relevant URLs

https://mapknitter.org

### PublicLab.org username
igniteeng000
(to help reproduce the issue)

### Browser, version, and operating system
chrome, ubuntu/windows

For bug reports, fill out the above template; for feature requests, you can delete the template.

### PR DESCRIPTION
**Pull request by divyabaid16**
Fixes #570 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

Peek 2019-06-13 09-44

[//]: # (To mark checkbox write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

Thanks!

### CODE REVIEW

**Comment by divyabaid16** [comment]
@publiclab/mapknitter-reviewers

**Comment by jywarren** [comment]
Oh wow! OK, this moves anonymous maps to its own area? If so, this is awesome, thanks! @stefannibrasil be aware of this change that could have an effect on the new front page too.

**Comment by jywarren** [comment]
Actually, could we make the text in the tabs not be header text, but just normal sized? Thank you!

**Comment by jywarren** [comment]
Great!!!!

**Pull request merged**
