### PR TITLE
New travis config and rails4

### PR DESCRIPTION
**Pull request by cesswairimu**
Test if new travis config will finish if added to rails 4 upgrade branch

### CODE REVIEW

**Comment by cesswairimu** [comment]
Hi @alaxalves pulled your branch onto mine and travis ran to completion :tada: :tada: 
This is how the output looks like.  
Screenshot from 2019-05-27 02-53-58

:heart: :heart: 
I can not view the whole output as a whole though.
Is there something  we can add so that we can view the whole build log and also these awesome sub-logs?
Thanks

**Comment by kaustubh-nair** [comment]
> I can not view the main output as a whole though.
> Is there something we can add so that we can view the whole build log and also these awesome sub-logs?
> Thanks

Hey Cess, you can view the logs by clicking on the failing jobs right?
I don't think viewing the whole log together is necessary? 
Thanks!

**Comment by alaxalves** [comment]
> Hi @alaxalves pulled your branch onto mine and travis ran to completion  
> This is how the output looks like.
> Screenshot from 2019-05-27 02-53-58
> 
>  
> I can not view the main output as a whole though.
> Is there something we can add so that we can view the whole build log and also these awesome sub-logs?
> Thanks

That's great news @cesswairimu. I think that a good next move would be merging #605 into #578. After this we could start working on the problematic controller test. Meanwhile @kaustubh-nair will keep his good work by increasing our test coverage. I'll keep working in our DevOps infra(it's almost done) and I'll start getting more in touch with you @cesswairimu to get #578 fully merged. What do you think, is that a good workplan for those next days? @jywarren @sashadev-sky @icarito tell us what you think too.

**Comment by cesswairimu** [comment]
@alaxalves yeah sounds like a plan. I think the new travis config should be merged to main though so that others can take advantage of it in the meantime. As for the failing test did you test it on your main to see if it fails for you too? I ran the tests on code envy and it was failing there too. I have been trying to fix it but I cannot find the reason why the file is not being created during export.

**Comment by kaustubh-nair** [comment]
> 
> That's great news @cesswairimu. I think that a good next move would be merging #605 into #578. After this we could start working on the problematic controller test. Meanwhile @kaustubh-nair will keep his good work by increasing our test coverage. I'll keep working in our DevOps infra(it's almost done) and I'll start getting more in touch with you @cesswairimu to get #578 fully merged. What do you think, is that a good workplan for those next days? @jywarren @sashadev-sky @icarito tell us what you think too.
> 
> PS @cesswairimu : I have split the build logs on purpose, since it makes easier to debug which test is failing, makes our build faster..... and so on. Basically I took the `rake test:all` and splitted it, summarizing our entire test suite is still running, but in parallel now.
I will soon be done with the test coverage. After that @cesswairimu I can give your upgrade some help if you'd like. We should push the upgrade to `unstable` (Mapknitter has an `unstable` right?) so everyone can test it and create issues.
A good step after that would be changing Bower to Yarn (https://github.com/publiclab/mapknitter/issues/351)

**Comment by alaxalves** [comment]
> > That's great news @cesswairimu. I think that a good next move would be merging #605 into #578. After this we could start working on the problematic controller test. Meanwhile @kaustubh-nair will keep his good work by increasing our test coverage. I'll keep working in our DevOps infra(it's almost done) and I'll start getting more in touch with you @cesswairimu to get #578 fully merged. What do you think, is that a good workplan for those next days? @jywarren @sashadev-sky @icarito tell us what you think too.
> > PS @cesswairimu : I have split the build logs on purpose, since it makes easier to debug which test is failing, makes our build faster..... and so on. Basically I took the `rake test:all` and splitted it, summarizing our entire test suite is still running, but in parallel now.
> 
> I will soon be done with the test coverage. After that @cesswairimu I can give your upgrade some help if you'd like. We should push the upgrade to `unstable` (Mapknitter has an `unstable` right?) so everyone can test it and create issues.
> A good step after that would be changing Bower to Yarn (#351)

Totally agree, Bower is something that needs quick replacement

**Comment by cesswairimu** [comment]
Sounds like a plan thanks @alaxalves and @kaustubh-nair

**Comment by alaxalves** [comment]
Hey @cesswairimu, I have just finished https://github.com/publiclab/mapknitter/pull/605 maybe you could merge it into this to test it out. :smile:

**Comment by cesswairimu** [comment]
Closing this... the travis changes were merged to main.

**Pull request closed without merging**
