### PR TITLE
Bootstrap 4 small button fixes

### LINKED ISSUE #487: button styling for "Place" button
It looks like in the Bootstrap 4 upgrade, some buttons didn't quite get restyled- this `Place` button and perhaps it's neighbor are appearing as plain text:

image

https://github.com/publiclab/mapknitter/blob/8901fb0d0b982abd549af64ed09f48720a5ffe8e/app/views/images/_index.html.erb#L21-L22

### PR DESCRIPTION
**Pull request by stefannibrasil**
Fixes #487 

Those small issues passed by, I'm glad you noticed them, @jywarren . I ran through the app and I _think_ all the old buttons are fixed now. Thanks!

### CODE REVIEW

**Comment by stefannibrasil** [comment]
Screenshot_2019-04-04 MapKnitter Testing Bootstrap 4

**Comment by stefannibrasil** [comment]
Screenshot_2019-04-04 MapKnitter Testing Bootstrap 4(1)

**Comment by stefannibrasil** [comment]
Screenshot_2019-04-04 MapKnitter

**Comment by stefannibrasil** [comment]
let me know if there is something else to be fixed here :+1:

**Comment by jywarren** [comment]
Awesome job, and so fast!

**Pull request merged**
