### PR TITLE
Attempt to install codecov

### PR DESCRIPTION
**Pull request by jywarren**
#467 #491 #531

### CODE REVIEW

**Comment by kaustubh-nair** [comment]
Are we switching to codecov instead of coveralls?
This would be great! We wouldn't have security issues of making the token public

**Comment by jywarren** [comment]
We tried it out in image-sequencer and it was very smooth, so I thought we
could try it here too. Do you prefer it?

**Comment by jywarren** [comment]
I can't get it to make comments like it did on image sequencer...

**Comment by jywarren** [comment]
Oh I guess I need to install a gem or something?

**Comment by jywarren** [comment]
Working from https://github.com/publiclab/image-sequencer/pull/1014

**Comment by kaustubh-nair** [comment]
Looks like you forgot to modify the travis file

**Comment by kaustubh-nair** [comment]
Oh you just did :smile:

**Comment by kaustubh-nair** [comment]
Travis logs say,
`--> No coverage report found.`
Looks like we need to generate the report before uploading it to Codecov.
Should we try installing the `Simplecov` gem?
It should generate the reports for us.

**Comment by alaxalves** [comment]
> Travis logs say,
> `--> No coverage report found.`
> Looks like we need to generate the report before uploading it to Codecov.
> Should we try installing the `Simplecov` gem?
> It should generate the reports for us.

Yes, in order to get this working we need to install simplecov gem and set it up in our `test_helper.rb` file as in [here](https://gitlab.com/klara-org/klara-api/blob/master/test/test_helper.rb#L3). Also, if we get CodeCov and SimpleCov properly set up here we could easily do what I have suggested in https://github.com/publiclab/mapknitter/issues/495#issue-430099366 FYK this example displayed is set using CodeCov/SimpleCov.

**Comment by kaustubh-nair** [comment]
Okay, let's do it

**Comment by kaustubh-nair** [comment]
Rubocop is being really strict :/
We should add a config file and remove whatever config options we don't need

**Comment by alaxalves** [comment]
> Rubocop is being really strict :/
> We should add a config file and remove whatever config options we don't need

I got a sample yml I used in previous projects, I'll MR it and we could discuss its rules we'd want.

**Comment by jywarren** [comment]
awesome, folks! Yeah, Rubocop is also just not very nice when it leaves
comments... "violations" isn't very friendly! let's turn it way down until
we can tune it a bit.

**Comment by kaustubh-nair** [comment]
I added the gem but it still doesn't seem to be sending the reports
Any idea what's wrong here?

**Comment by kaustubh-nair** [comment]
yay! :smile:

**Comment by kaustubh-nair** [comment]
The coverage report was not accessible from inside the docker container. So I created a shared volume to store the report there.

**Comment by kaustubh-nair** [comment]
It seems the docker volume was not necessary after all..
Anyway, @jywarren this is ready for merge! :smiley:

**Comment by jywarren** [comment]
Oooh what a pretty graph! Merging this!!!!!

**Comment by jywarren** [comment]
@cesswairimu check it out! 👀

**Comment by jywarren** [comment]
@publiclab/plots2-reviewers @publiclab/reviewers would we like this to be installed on `plots2` as well?

**Comment by cesswairimu** [comment]
Wow this looks amazing @jywarren @kaustubh-nair  :tada: :tada: . How do I get it to comment on my PR just rebased but can't see the bot :eyes:

**Comment by cesswairimu** [comment]
My bad, I see the bot now :smiley:

**Pull request merged**
