### PR TITLE
Travis yml from jywarren/mapknitter

### PR DESCRIPTION
**Pull request by icarito**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- `rake test`
* [ ] code has been rebased on top of latest master (check if another pull request was added recently, and please rebase)
* [ ] pull request is descriptively named and, if possible, multiple commits squashed if they're smaller changes

Thanks!

### CODE REVIEW

**Comment by icarito** [comment]
We should get:
```
$ docker-compose run web bash -c "rake db:setup"
rake aborted!
LoadError: Please install the mysql2 adapter: `gem install activerecord-mysql2-adapter` (can't activate mysql2 (~> 0.3.10), already activated mysql2-0.4.5. Make sure all dependencies are added to Gemfile.)

Gem::LoadError: can't activate mysql2 (~> 0.3.10), already activated mysql2-0.4.5. Make sure all dependencies are added to Gemfile.

Tasks: TOP => db:setup => db:schema:load_if_ruby => db:create                          (See full trace by running task with --trace)      
```

**Comment by icarito** [comment]
I'm comparing mapknitter current Gemfile with the one we have in priv1 instance. The only difference that I see is that it specified an older Rake. Did we upgrade rake?

**Comment by jywarren** [comment]
Hmm, I don't know that we needed to if we did. Darn, this looks like it was much more troublesome than we'd thought... sorry to derail you from the Solr work!

**Comment by icarito** [comment]
You did mention this wasn't a priority so I'll resume work on Solr!

BTW I have an instance of this for testing in
/srv/mapknitter_branch1/mapknitter at tycho.

**Comment by icarito** [comment]
This is as far as I got, looks like an issue in the schema?
```
-- assume_migrated_upto_version(20150715162314, ["/app/db/migrate"])
   -> 0.0626s
rake aborted!
NoMethodError: undefined method `accept' for nil:NilClass
Tasks: TOP => db:abort_if_pending_migrations
```

**Comment by jywarren** [comment]
Found possible fix via https://stackoverflow.com/questions/12730190/rails-mysql2-undefined-method-accept-for-nilnilclass#13787696

**Comment by jywarren** [comment]
Finally!!!

**Pull request merged**
