### PR TITLE
Fixes #889 - Update initializers to class factory syntax

### LINKED ISSUE #889: Update initializers to class factory syntax ||
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/mapknitter/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

**What's supposed to happen:**

From the official [Leaflet docs](https://leafletjs.com/reference-1.0.0.html):
<blockquote>

Class Factories
You may have noticed that Leaflet objects are created without using the new keyword. This is achieved by complementing each class with a lowercase factory method:

new L.Map('map'); // becomes:
L.map('map');

</blockquote>

**What actually does happen:**

We use Leaflet's built-in `L.TileLayer` but we don't take advantage of their suggested class factory syntax. 

## Solution

1. remove the `new` keyword and change the initializer to `L.tileLayer`
https://github.com/publiclab/mapknitter/blob/fb876407671f27e0bc97cb9da1edb2baa8797ac0/app/views/map/_leaflet.html.erb#L50

2. this one was was written half correctly - just remove the `new` keyword here
https://github.com/publiclab/mapknitter/blob/fb876407671f27e0bc97cb9da1edb2baa8797ac0/app/views/map/_leaflet.html.erb#L53

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo [README instructions](https://github.com/publiclab/mapknitter/blob/main/README.md)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, an additional checklist will be provided for getting it merged

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

### PR DESCRIPTION
**Pull request by sriddbs**
Fixes #889 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/mapknitter-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@sriddbs I can't merge unless the Travis tests pass. I made a very big PR 30 minutes ago and it went through - so I would try just rebasing! Let me know if you need help with that! 

Or you can sit tight until @alaxalves @kaustubh-nair see this they might be familiar with this error

**Comment by sriddbs** [comment]
@sashadev-sky I can try rebase with `main` branch. Please let me know if I should

**Comment by sashadev-sky** [comment]
@sriddbs yeah go for it! Thanks!

**Comment by sriddbs** [comment]
@sashadev-sky  This is what I will follow in my local repo

* git remote add upstream git@github.com:publiclab/mapknitter.git
* git pull upstream main
* git checkout `<my-branch>`
* git rebase main
* git push origin `<my-branch>`

is this correct?

**Comment by sashadev-sky** [comment]
@sriddbs Yes perfect. Also after `$ git pull upstream main` you can optionally do `$ git push origin main` as well to update your main branch in your remote origin repo too. I always do this

**Comment by sriddbs** [comment]
@sashadev-sky thanks :) is there anything else I can work on?

**Comment by sashadev-sky** [comment]
@sriddbs yes! What are you interested in?

**Comment by sriddbs** [comment]
@sashadev-sky I can take up any other small issues or enhancements to contribute more. I am very much comfortable programming with Ruby on Rails. I like to be involved more in the open-source community, so if you have anything else for me, please let me know.

**Comment by sriddbs** [comment]
@sashadev-sky I had taken up first-timers-only task few months back and would love to contribute more, so is there anything else I can work on?

**Pull request merged**
