### PR TITLE
ADD: "Create a collection" button

### LINKED ISSUE #808: "Create a collection" button on view page
Our new view pages #761 will be awesome. Given that tags can be used to make a collection of maps (see #807), let's put a note by the tag input that suggests `Make a collection of maps` and explains that using a unique tag on a set of maps creates a page at `https://mapknitter.org/tag/_____` where you can show your maps together.

------
We are participating in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more

### PR DESCRIPTION
**Pull request by VladimirMikulic**
Is this something that you had in mind? Here is my button:

Screenshot_20200106_230218

Clicking on the button displays the modal with a message:

Screenshot_20200106_230244

Resolves #808 

@ananyaarun @cesswairimu @jywarren could you take a look at this? Thanks.

### CODE REVIEW

**Comment by jywarren** [comment]
Oh wow that is AWESOME! This is great! Is it ready for a merge?

**Comment by jywarren** [comment]
It sure seems so!

**Comment by VladimirMikulic** [comment]
@jywarren I wouldn't have submitted the PR if the feature wasn't ready :)

**Comment by VladimirMikulic** [comment]
@cesswairimu @ananya could you approve this task on GCI dashboard? Thanks.

**Comment by cesswairimu** [comment]
done...thanks for working on this

**Comment by VladimirMikulic** [comment]
@cesswairimu thank you :+1:

**Comment by jywarren** [comment]
Just noting that an extra "this is ready" is nice because we actually encourage folks to upload their PRs early for feedback, and just to show others that the issue is being worked on already, so there's no duplication of efforts! No big deal just thought that might be helpful info!

**Comment by VladimirMikulic** [comment]
@jywarren thanks, I'll do that in the future :+1: I usually submit the PR once it is ready for merge, not before that.

**Pull request merged**
