### PR TITLE
Card Enhancement

### LINKED ISSUE #1660: Card Alignment Enhancement
### Problem

The cards ( of[ Map Gallery](https://mapknitter.org/gallery))and its details are not align in according to the different screen resolution 

### Relevant URLs
https://mapknitter.org/gallery

card-alignment

### PR DESCRIPTION
**Pull request by asaayushisingh**
Fixes #1660 (<=== Add issue number here)

**Card and their details of Map Gallery are not aligned according to the different screen resolutions**
### Before--->

WhatsApp Image 2022-04-18 at 7 07 01 PM

### After--->

image-centering

[//]: # (To mark checkbox write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/mapknitter-reviewers` for help, in a comment below

Thanks!

### CODE REVIEW

**Comment by cesswairimu** [comment]
Hi @asaayushisingh, there is a conflicting file here, probably from your PR we just merged. kindly rebase, this is looking good. Thanks for working on this

**Comment by asaayushisingh** [comment]
Hey! @cesswairimu Kindly review the changes!..Thank You!

**Comment by asaayushisingh** [comment]
Hey! @cesswairimu Kindly review the changes!..Thank You!

**Review by cesswairimu — APPROVED** [review]
Great :tada: thanks a bunch for opening and fixing this :100:

**Pull request merged**
