### PR TITLE
Sort author list 

### LINKED ISSUE #517: Add search and sort feature in author list
Enhancement Idea.
Add search and sort feature in author list to find author infromation easily.

Link: https://mapknitter.org/users

### PR DESCRIPTION
**Pull request by igniteeng000**
Fixes #517 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by igniteeng000** [comment]
@pubbliclab/reviewers please review

**Comment by igniteeng000** [comment]
@publiclab/reviewers @jywarren please review it again. I have fixed some codeclimate issues.

**Comment by igniteeng000** [comment]
Should I squash my commits?

**Comment by jywarren** [comment]
Awesome!!!!!

**Comment by jywarren** [comment]
Not needed, thanks! GitHub can squash it for us. 🎉

**Pull request merged**
