### PR TITLE
Cache featured mappers

### LINKED ISSUE #767: Optimization of front page
Hi @cesswairimu I realized that stable front page is quite slow and that it's most likely the listing of mappers. I think we need to make a cache around that -- at least for now, and then somehow optimize that query... It's really slow, and makes sense because it's counting all maps?

We can work on this on Monday!

### PR DESCRIPTION
**Pull request by cesswairimu**
Fixes #767

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/mapknitter-reviewers` for help, in a comment below

### CODE REVIEW

**Comment by jywarren** [comment]
Hi @cesswairimu sorry i'm working on the "featured via tags" version here!

**Comment by jywarren** [comment]
I can't get the fullhash thing working though. Do you know how to enable it? I want to get the "featured regions" row just under the map to move the map but not reload the whole page!

**Comment by jywarren** [comment]
https://github.com/publiclab/mapknitter/pull/775

**Comment by jywarren** [comment]
Like this! https://mapknitter.org/#2/43.0/2.8/

**Comment by jywarren** [comment]
aha -- `var hash = new L.Hash(Mapknitterunique);`

**Comment by cesswairimu** [comment]
Gotcha aha awesome

**Comment by cesswairimu** [comment]
Closing this going with another implementations

**Comment by jywarren** [comment]
Awesome. Also I'm a bit stuck on https://github.com/publiclab/leaflet-environmental-layers/pull/219 and https://github.com/publiclab/leaflet-environmental-layers/pull/220...

**Comment by cesswairimu** [comment]
okay taking a look

**Pull request closed without merging**
