### PR TITLE
add confirmation for map submit

### LINKED ISSUE #1025: should give warning about "return to editor" being permanent save for anon maps
We have an ability to create a map without login-in, these maps are marked as created by "anonymous".  During creation of such a map, when you click on "return to editor" means permanent save, since a not logged in user cannot edit/delete maps. 

### To do
We need to add a warning about clicking on "create map" button being permanent save for anonymous maps. This is the  button https://github.com/publiclab/mapknitter/blob/main/app/views/maps/new.html.erb#L76

### Relevant URLs
https://mapknitter.org/maps/new

--------------------------------------------
We are participating in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more

### PR DESCRIPTION
**Pull request by Uzay-G**
Fixes #1025
@publiclab/mapknitter-reviewers 
Hi, this pull request will warn anonymous users when they decide to make their map that they will no longer be able to edit it. On the other hand, it does not warn logged in users who can edit their maps.
What do you think?
Thanks! :+1:

### CODE REVIEW

**Comment by Uzay-G** [comment]
What do you think @cesswairimu and @ananyaarun

**Comment by cesswairimu** [comment]
Great :tada: can we get a gif for this? Thanks @Uzay-G

**Comment by Uzay-G** [comment]
Yeah no problem @cesswairimu. Here you go:
mapknitter-confirm

**Comment by Uzay-G** [comment]
Thanks, I will claim the task once I can.

**Pull request merged**
