### PR TITLE
Added feeds links

### LINKED ISSUE #434: Add RSS feed links to the page footer
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/views/layouts/_footer.html.erb](https://github.com/publiclab/mapknitter/blob/main/app/views/layouts/_footer.html.erb) in the `mapknitter` repository (press the little pen Icon) and edit the line as shown below. 

To get help installing the application on your computer, see [the project README](https://github.com/publiclab/mapknitter/tree/main/README.md) and get help at #307 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -8,8 +8,15 @@
       <p>
         Having trouble? <a href="http://github.com/publiclab/mapknitter/issues">Submit bugs here</a>.
       </p>
-        <p>
-          MapKnitter uses <a href="http://gdal.org">GDAL</a>, <a href="http://leafletjs.com">Leaflet</a>, <a href="http://rubyonrails.org">Ruby on Rails</a>, <a href="http://imagemagick.org">ImageMagick</a>, and other open source software, and makes extensive use of the open source font <a href="http://www.theleagueofmoveabletype.com/junction">Junction</a>.</p>
+      <p>
+        MapKnitter uses <a href="http://gdal.org">GDAL</a>, <a href="http://leafletjs.com">Leaflet</a>, <a href="http://rubyonrails.org">Ruby on Rails</a>, <a href="http://imagemagick.org">ImageMagick</a>, and other open source software, and makes extensive use of the open source font <a href="http://www.theleagueofmoveabletype.com/junction">Junction</a>.
+      </p>
+      <h3>Feeds</h3>
+      <p><a href="/feeds/all">All maps</a></p>
+      <p><a href="/feeds/license/public-domain">Public domain maps</a></p>
+      <p><a href="/feeds/license/cc-by-sa">CC-BY-SA maps</a></p>
+      <p><a href="/feeds/license/cc-by">CC-BY maps</a></p>
+      <p><a href="/feeds/tag/barataria">Maps of Barataria Bay</a></p>
     </div>
     <div class="col-md-4">
       <h3>Contributing</h3>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by Welquer**
Fixes #434  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by alaxalves** [comment]
@Welquer I have made some considerations in #606 that would apply here too. :D Maybe you check there.

**Comment by Welquer** [comment]
Thank you too @alaxalves. I also don't like the idea of having a long line, mainly because it interrupts your vertical reading, so you need to horizontally scroll. As it was my first PR on an open source project (🎉), I did as required on the description (just copy and paste), that's why it is as it is. Adding my 2 cents, I'd break it as follows (readability is better):

<p>
        MapKnitter uses <a href="http://gdal.org">GDAL</a>,&nbsp;
        <a href="http://leafletjs.com">Leaflet</a>,&nbsp;
        <a href="http://rubyonrails.org">Ruby on Rails</a>,&nbsp;
        <a href="http://imagemagick.org">ImageMagick</a>,&nbsp;
        and other open source software, and makes extensive use of the open source font&nbsp;
        <a href="http://www.theleagueofmoveabletype.com/junction">Junction</a>.
 </p>

What do you think about it?

**Comment by alaxalves** [comment]
> Thank you too @alaxalves. I also don't like the idea of having a long line, mainly because it interrupts your vertical reading, so you need to horizontally scroll. As it was my first PR on an open source project (), I did as required on the description (just copy and paste), that's why it is as it is. Adding my 2 cents, I'd break it as follows (readability is better):
> 
> MapKnitter uses [GDAL](http://gdal.org),  [Leaflet](http://leafletjs.com),  [Ruby on Rails](http://rubyonrails.org),  [ImageMagick](http://imagemagick.org),  and other open source software, and makes extensive use of the open source font  [Junction](http://www.theleagueofmoveabletype.com/junction).
> 
> What do you think about it?

I like it that way, what do you think @jywarren ?

**Comment by sashadev-sky** [comment]
@Welquer Thank you for the PR and sorry for the delay here! There has been a lot going on with mapknitter this month!! 

One quick tip about your PR: you need to reference the original opened issue to make sure its linked there and we notice your PR. do this by replacing fixes #0000 with the corresponding issue #.

For your PR, it will need a rebase since there have been merged updates to the file since you last pulled it. Let me know if you need help on this! 

As for the code, the extended line doesn't bother me so much but @alaxalves is right that the lines should not be so long and it's a good thing to enforce. With FTOs it is just a copy paste situation so dw! But if you could split the line and push another commit that'd bee great! Thanks :)

**Comment by cesswairimu** [comment]
This PR has been open for a long time and no activity/ reviews requested has not been addressed. We understand you might be busy and engaged on other things. I am closing this for now...please  feel free to reopen if you get some time and would like to finish this. Rem to check if its still available before you reopen. Thanks

**Pull request closed without merging**
