### PR TITLE
Anonymous map option added

### LINKED ISSUE #719: "log in" button not working
### What happened just before the problem occurred
I'm on google chrome, and went to Mapknitter to search for some maps. I'm not logged in on this computer, but when I tried to use the button on the left-hand side of the page, it wasn't working. I kept getting a flash of a dropdown, but nothing happens when I click it.

Screen Shot 2019-06-18 at 10 06 49 AM

### PublicLab.org username
stevie

### PR DESCRIPTION
**Pull request by divyabaid16**
Fixes #719 
https://github.com/publiclab/mapknitter/issues/719#issuecomment-509428687

Peek 2019-07-09 13-06

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/mapknitter-reviewers` for help, in a comment below

Thanks!

### CODE REVIEW

**Comment by divyabaid16** [comment]
@jywarren please let me know if there is any other change needed.
Thanks!

**Comment by jywarren** [comment]
This is LOVELY.

Let's also add a note: "Anonymous maps have some limitations. Click here to
learn more."

And, do you think we should show the login options in this new box?

**Comment by divyabaid16** [comment]
Okay, @jywarren I will add the limitations. 
I have listed down a some limitations, do add more if I have missed out something.
- You cannot post comments on maps and be part of the discussion.
- You cannot export featured maps.
- You cannot delete the images.

And regarding the Log in thing, I think it doesn't really matter if the link is preset there or not. So if not required I will remove it.

Thanks!

**Comment by jywarren** [comment]
Oh, actually i really like that it prompts you to log in one more time. I
meant, maybe we should have the "quick log in with Google/Facebook/Twitter"
buttons appear here too to make it extra smooth to log in?

Love this list of limitations. maybe "You cannot delete the images --
because as an anonymous user we can't tell whose images they are or who
should be allowed to delete them" ? Does that make sense?

**Comment by divyabaid16** [comment]
Oops, I guess I forgot to add the screenshot of the anonymous page that it is redirected to.
Selection_205

@jywarren 
Thanks!

**Comment by jywarren** [comment]
OH i 'm sorry, this looks great. Ready for a merge? Thank you!!

**Comment by divyabaid16** [comment]
Ya, this is ready. Thanks!

**Comment by jywarren** [comment]
Great, thank you!!!

**Pull request merged**
