### PR TITLE
Remove navbar overlap

### LINKED ISSUE #1611: Navbar overlapping site content
### What happened just before the problem occurred
Bootstrap fixed-top navbar is overlapping the site content, thus notifications are not completely visible.

https://user-images.githubusercontent.com/85152262/157945224-a73748a3-1eca-4806-8dc4-76cb58dac068.mp4

Specifically, for a particular screen size the content hides behind the navbar.

navbar-overlapping

### Relevant URLs

https://mapknitter.org/
https://mapknitter.org/gallery

Browser - Google Chrome
Version - 99.0.4844.51
OS -Ubuntu 20.04

### PR DESCRIPTION
**Pull request by sakshi-2412**
Fixes #1611  (<=== Add issue number here)

Changed navbar bootstrap class so that it does not overlap with site content, specially notifications.

Before ->

https://user-images.githubusercontent.com/85152262/158656373-25490865-e83d-4762-b30c-6c6cea669368.mp4

After ->

https://user-images.githubusercontent.com/85152262/158656600-b8a488ac-dcb2-4fdb-85ff-df41f9f852fb.mp4

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/mapknitter-reviewers` for help, in a comment below

### CODE REVIEW

**Comment by jywarren** [comment]
Hi @sakshi-2412 thank you very much - i've reopened it to try to trigger the tests again, as they had gotten stuck. Looks like they're running now, so let's see!

**Comment by jywarren** [comment]
Looks like it worked smoothly! Thank you very much!

**Comment by jywarren** [comment]
I'm sorry to ask one more thing, but could you open it on a map itself, a page like https://mapknitter.org/maps/us-states/edit - to ensure that such pages work normally with the changes? You might have to create a map at `/maps/new` to test this out. Actually, that page uses the same template as an actual map, so you should be able to just go to `/maps/new` to see if the changes work in that alternative layout. Thank you so much!!!

**Comment by sakshi-2412** [comment]
hey @jywarren , yes I just checked and it seems that map create and edit pages have a different layout, so header is not displaying correctly. I'll have to tweak the header rendering a bit in these pages and I think it should work well.

Original ->

original

With current changes ->

current

With new changes ->

new


I'll just check again if the header is displaying correctly everywhere :sweat_smile:

**Comment by jywarren** [comment]
Excellent, thank you for checking and correcting. Merging now!

**Pull request merged**
