### PR TITLE
Fix login problem

### PR DESCRIPTION
**Pull request by kaustubh-nair**
Fixes https://github.com/publiclab/mapknitter/issues/679

### CODE REVIEW

**Comment by kaustubh-nair** [comment]
@publiclab/mapknitter-reviewers I've tested this on unstable successfully. Lets merge this asap since login doesn't work on https://mapknitter.org either

**Comment by jywarren** [comment]
Thanks for quickly addressing this!

**Comment by rarrunategu1** [comment]
Hi @kaustubh-nair @jywarren , unfortunately when running my tests on local the local login test doesn't pass.  Maybe that needed to be updated too?  Should we open another issue for this?

image

**Comment by kaustubh-nair** [comment]
Yes @rarrunategu1, let's open a new issue to address this.
Thanks

**Comment by rarrunategu1** [comment]
Weird, I just ran the test again and it passed.  I don't understand why it didn't pass last time.

**Pull request merged**
