### PR TITLE
Add default value for bands string in exporter

### LINKED ISSUE #912: export not working
### What happened just before the problem occurred
I'm trying to help someone download a map so they can get it printed, but the export currently isn't working. I can get the image on a jpeg from the cloud export, but we're looking for a larger file than this. 

### Relevant URLs

https://mapknitter.org/maps/nottingham-city-centre### PublicLab.org username

### PR DESCRIPTION
**Pull request by cesswairimu**
Fixes #912 

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/mapknitter-reviewers` for help, in a comment below

### CODE REVIEW

**Comment by cesswairimu** [comment]
@publiclab/mapknitter-reviewers, could someone please pull this locally and just make sure it is working. Thanks

**Comment by sashadev-sky** [comment]
@cesswairimu hi cess! I remember this error when I was building the exports controller actions. I had fixed it directly in the controller by passing an empty bands string, will look into why it came back! 

And also check your solution. It would definitely be better to actually just fix the database table

**Comment by sashadev-sky** [comment]
seeing the code for that is still there:

https://github.com/publiclab/mapknitter/blob/a79a86f2af01a7d1b5a9623616fd043228ebb267/app/controllers/export_controller.rb#L84-L92

**Comment by jywarren** [comment]
Hi, all - ok, I'm going to merge this and republish MapKnitter with it to address the immediate issue. I agree we should solve this more thoroughly later with a db migration. Thanks!

**Comment by cesswairimu** [comment]
Thanks @sashadev-sky and @jywarren ..I will create a follow-up issue for adding the migration

**Pull request merged**
