### PR TITLE
GDAL export container

### PR DESCRIPTION
**Pull request by icarito**
I've created a Dockefile to define an image of GDAL  2.4.1 + Imagemagick + Ruby 2.5.

**You can try this ** by getting the already-built image from Docker-hub!

run `docker run icarito/gdal_ruby_imagemagick:buster`

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- `rake test`
* [ ] code has been rebased on top of latest master (check if another pull request was added recently, and please rebase)
* [ ] pull request is descriptively named and, if possible, multiple commits squashed if they're smaller changes

Thanks!

### CODE REVIEW

**Comment by icarito** [comment]
This PR seems to have some artifacts of another branch, I'll clean it up, sorry!

**Comment by jywarren** [comment]
What do you think the best minimal interface is to connect export.rb to the outside world? I'd guess it's probably going to be more efficient than Rails to have a more minimal way to initiate commands to `export.rb` and provide HTTP progress responses as it runs (say, static JSON files with status).

**Comment by jywarren** [comment]
Also, I wonder if you could try setting up the container without the Rails app but with `minitest`, so we can run the tests from `/test/unit/exporter_test.rb` (from #341) on this stand-alone version of the exporter?

**Comment by jywarren** [comment]
Connecting back to https://github.com/googleapis/google-cloud-ruby from the resources issue in https://github.com/publiclab/mapknitter/issues/296, which may be a good template for a cloud service in Ruby.

**Comment by jywarren** [comment]
Aha - added these to #296 but see:


* https://cloud.google.com/ruby/rails/
* https://cloud.google.com/appengine/docs/flexible/ruby/

**Comment by jywarren** [comment]
Yes! `The Hello World app is a very basic one-file Sinatra application` -- sinatra, i guess, then!

**Comment by jywarren** [comment]
https://github.com/GoogleCloudPlatform/ruby-docs-samples/tree/master/appengine/hello_world here it is!

**Comment by icarito** [comment]
Hi @jywarren I've made a Sinatra app that receives a posted warpable.json file and parses it, but I need some directions on how to trigger https://github.com/publiclab/mapknitter-exporter or even better if it could parse the json file itself ;-)

**Comment by jywarren** [comment]
Moving to https://github.com/publiclab/mapknitter-exporter-sinatra/pull/1

**Pull request closed without merging**
