### PR TITLE
Fix image placement

### LINKED ISSUE #950: Images not being placed
On clicking the `Place` button, nothing happens. This image does not turn up on the map
This is due to some weird ordering issues of the dependencies for the assets. I had solved this in `rails-5` but maybe it got messed up during some merge conflicts?

### PR DESCRIPTION
**Pull request by kaustubh-nair**
Fixes #950 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/mapknitter-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by kaustubh-nair** [comment]
Hmm, maybe I can write a system test for this. This issue popped up really often during the upgrade

**Comment by jywarren** [comment]
That'd be awesome!

**Comment by jywarren** [comment]
Oh hm, @gauravano  and @sashadev-sky just worked on these files, I think? the `//=` will guide Sprockets to concatenate it in but `// =` won't, right?

**Comment by kaustubh-nair** [comment]
Oh is that so? I thought i

> Oh hm, @gauravano and @sashadev-sky just worked on these files, I think? the `//=` will guide Sprockets to concatenate it in but `// =` won't, right?

Yes, `// =` is invalid syntax and shouldn't work

**Comment by kaustubh-nair** [comment]
@jywarren I wrote the testing for pressing the `Place` button
But I've got no idea how to make sure the image got placed on the leaflet layer
Any pointers for this?

**Comment by kaustubh-nair** [comment]
The limits on the tables in the schema got modified? :thinking: How did that happen?

**Comment by jywarren** [comment]
Maybe a system test would work? You can run JavaScript in a system test --
https://github.com/publiclab/plots2/blob/master/test/system/post_test.rb#L36

As to schema, not sure! Check the blame view? A lot of changes got merged
this week!

**Comment by sashadev-sky** [comment]
If you mean the featureGroup by leaflet layer, you can check via the image’s _eventParents attribute. featureGroup is automatically added as 1st eventParent on img. 

I wrote the code so that images don’t store references to their parent group because structurally that would’ve been ideal but this is a sort of hidden way to check. 

@jywarren do you think I should just save the featureGroup instance on the image in LDI officially and expose it to api?

I have been avoiding it because I thought we might merge the single and multiple image interface together eventually.

But in any case you know everything check outs when you add the image to the featureGroup and not the map, and then see it on the map. 

Sasha Boginsky
Goizueta Business School
Emory University | BBA Class of 2017
646.241.5756 | sasha.boginsky@emory.edu

**Comment by kaustubh-nair** [comment]
Hi @sashadev-sky Sorry I've got very little familiarity with LDI
How do I find the feature group exactly? 
I tried to search for `featureGroup` by both ID and Class but I couldn't find any element like that

**Comment by sashadev-sky** [comment]
@kaustubh-nair I thought I responded to this from my phone, 

but featureGroup is `L.DistortableCollection`. It is an instance of Leaflet's `L.FeatureGroup`. Anyway, the bug being fixed here is actually unrelated to that now that I am looking over the issue. But lets definitely try to get this merged asap as its a core functionality! 

What are the issues still blocking merge?

**Comment by sashadev-sky** [comment]
@kaustubh-nair layers of all sorts are saved on the map and can be accessed via `map._layers`. So your check could do something like this:
```JS
var layers = map._layers;
for (var k in layers) { 
    if (layers[k] instanceof L.DistortableImageOverlay) {
        return true;
    }
}
``` 

L.DistortableImageOverlay is the class of an img element

**Comment by kaustubh-nair** [comment]
The issue has been fixed. I'm asking all this so that I can write a system test for it.

On 20-Aug-2019 7:30 AM, Sasha Boginsky <notifications@github.com> wrote:

@kaustubh-nair<https://github.com/kaustubh-nair> I thought I responded to this from my phone,

but featureGroup is L.DistortableCollection. It is an instance of Leaflet's L.FeatureGroup. Anyway, the bug being fixed here is actually unrelated to that now that I am looking over the issue. But lets definitely try to get this merged asap as its a core functionality!

What are the issues still blocking merge?

**Comment by sashadev-sky** [comment]
@kaustubh-nair yes understood let me know if my last comment helps!

**Comment by kaustubh-nair** [comment]
Awesome!
Thanks you so much @sashadev-sky !!!
@jywarren Please review, this is ready!

**Comment by jywarren** [comment]
This is awesome. Great work!!!

**Pull request merged**
