### PR TITLE
Replace ftools for fileutils (ftools is deprecated)

### PR DESCRIPTION
**Pull request by icarito**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test` (tested in production)
* [x] code has been rebased on top of latest master (check if another pull request was added recently, and please rebase)
* [x] pull request is descriptively named and, if possible, multiple commits squashed if they're smaller changes

Thanks!

ftools has been deprecated since Ruby 1.9.1

### CODE REVIEW

**Comment by jywarren** [comment]
Are you confident this'll run in our current production environment? Thanks!

**Comment by icarito** [comment]
Yes, in fact I am surprised it ran without it.
```
mapknitter@tycho2:~/production/app/models$ ruby --version
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]
mapknitter@tycho2:~/production/app/models$ ruby
require "ftools"
/srv/mapknitter-app/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- ftools (LoadError)
        from /srv/mapknitter-app/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -:1:in `<main>'
mapknitter@tycho2:~/production/app/models$ ruby
require "fileutils"
mapknitter@tycho2:~/production/app/models$ 
```

**Comment by jywarren** [comment]
Super. I'll merge into stable. Thanks!

**Comment by jywarren** [comment]
Done!

**Comment by icarito** [comment]
The reason it is not noticed in production is that apparently this code path is only reached when using local file storage, not AWS S3.

**Pull request merged**
