### PR TITLE
UI improvements: version tracking and other in the sidebar

### PR DESCRIPTION
**Pull request by divyabaid16**
Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

The button is removed:
Selection_225

Sort option is made better:
Selection_226

[//]: # (To mark checkbox write 'x' within the square brackets)

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/mapknitter-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by divyabaid16** [comment]
@gauravano @cesswairimu @jywarren

**Comment by jywarren** [comment]
Hi @divyabaid16 ! Thank you! Just a few suggestions, this is good!

1. How about we make the clock icon into a button like the others on the right side, and move it over there with them?
2. Could we make the "revert" button into a button styled like the others as well? 
3. could we add a tooltip to the Revert button that says "revert"?
4. Can we add an area to the top of the list of revisions that says `# revisions. Learn more` where `Learn more` links to a page at https://publiclab.org/mapknitter-version-tracking, which we'll create, that has some extra documentation? 

Thank you! This is such an amazing feature!

**Comment by divyabaid16** [comment]
@jywarren, here is the updated screenshot:
Selection_229

**Comment by divyabaid16** [comment]
The codecov/project is failing. I guess there is some issue in feeds_controller.rb

**Comment by jywarren** [comment]
That's oK, i think Kaustubh is working on a fix for the CodeCov configuration... this looks great, but we're trying to resolve the export downloads tab and then the Rails 5 PR first, so Alax doesn't have to keep rebasing. This is good to merge but let's try to go after those two? Thanks!

**Comment by divyabaid16** [comment]
Okay!

**Comment by divyabaid16** [comment]
I rebased my PR @jywarren 
Thanks!

**Comment by jywarren** [comment]
Great!!! Done! Can you test it in stable once it builds? Thank you!

**Comment by divyabaid16** [comment]
Ya, I will do it.

**Pull request merged**
