### PR TITLE
Footer redesign

### LINKED ISSUE #1632: Changes Required in Frontend Design of Footer in Mapknitter Website
### Problem
Website - https://mapknitter.org/
### The current Footer Design is not proper
```
1. Hovering effects is not there for social media logos and texts
2. The footer is not aligned properly.
3.'MAPKNITTER' is not highlighted.
```
https://user-images.githubusercontent.com/67657066/162281187-34f66ebb-eb2b-415d-ad1e-c6fcad88e171.mp4

### PR DESCRIPTION
**Pull request by asaayushisingh**
Fixes #1632 (<=== Add issue number here)
Website---https://mapknitter.org/

### Before----->

https://user-images.githubusercontent.com/67657066/162292000-33f1e219-e8b5-41e5-88c3-27e0a73189f7.mp4

### After----->

https://user-images.githubusercontent.com/67657066/162293878-d8987f40-322a-4add-963e-c0d42590aca6.mp4

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/mapknitter-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by asaayushisingh** [comment]
@TildaDares @jywarren I'd appreciate it if I could get this pull request reviewed, Thank you!.

**Review by jywarren — CHANGES_REQUESTED** [review]
Hi, these changes are really nice and the use of the import statement as well. I did notice you have a couple unnecessary files added; would you be able to remove them? Once that's complete, we should be able to merge this, thank you!

* chromedriver_linux64.zip
* google-chrome.deb

**Comment by asaayushisingh** [comment]
> Hi, these changes are really nice and the use of the import statement as well. I did notice you have a couple unnecessary files added; would you be able to remove them? Once that's complete, we should be able to merge this, thank you!
> 
> * chromedriver_linux64.zip
> * google-chrome.deb

Yeah Sure! will do that

**Comment by asaayushisingh** [comment]
> Hi, these changes are really nice and the use of the import statement as well. I did notice you have a couple unnecessary files added; would you be able to remove them? Once that's complete, we should be able to merge this, thank you!
> 
> * chromedriver_linux64.zip
> * google-chrome.deb

Hey! I did the required changes. Kindly review it. Thank You!

**Review by cesswairimu — APPROVED** [review]
Looking good :tada: :tada: . Thanks for working on this :100:

**Comment by cesswairimu** [comment]
Hi @asaayushisingh,  it shows your PR is a draft, if you are done making the changes you can unmark it as a draft  and we can have it merged. Thanks

**Comment by asaayushisingh** [comment]
> Looking good 🎉 🎉 . Thanks for working on this 💯

Thank you!🎉 @cesswairimu

**Comment by asaayushisingh** [comment]
> Hi @asaayushisingh, it shows your PR is a draft, if you are done making the changes you can unmark it as a draft and we can have it merged. Thanks

Yeah! @cesswairimu  Done!💯

**Comment by asaayushisingh** [comment]
Hey! @jywarren , @cesswairimu , @TildaDares  I will appreciate your feedback on this PR. 😄  Thank You!

**Comment by cesswairimu** [comment]
Hi @asaayushisingh, I know Jeff is quite busy and it might be a while before he can review this again, I will dismiss his changes as you already addressed them so  I can be able to merge. Thanks for the patience.

**Comment by asaayushisingh** [comment]
Hey! @cesswairimu thank you ! 😄

**Pull request merged**
