### PR TITLE
Reorganize and consolidate templates

### LINKED ISSUE #550: Reorganize templates
Consolidate and reorganize editor vs. viewer vs. maps listing templates, exporter
templates for readability and maintainability

### PR DESCRIPTION
**Pull request by cesswairimu**
Fixes #550 and #565 

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by cesswairimu** [comment]
paginate

**Comment by jywarren** [comment]
awesome! Ready for a merge? Thanks!!!!

**Comment by cesswairimu** [comment]
No ready still working o n this thanks

**Comment by cesswairimu** [comment]
resize
resize all images to 200px height

**Comment by jywarren** [comment]
Oh this looks cool, but are the images stretched? If you look at plots2
dashboard code there is a way to show them cut off (overflow hidden)
instead of stretched. COuld be useful!

**Comment by cesswairimu** [comment]
Great, thanks Jeff

**Comment by cesswairimu** [comment]
home
@jywarren This is how it looks now. Still not satisfied but we can merge this for now but don't close the issue would love to do more on this. Thanks

**Comment by jywarren** [comment]
Ooh, is this ready to merge?

**Comment by cesswairimu** [comment]
Yes @jywarren its ready

**Comment by jywarren** [comment]
Awesome!

**Pull request merged**
