### PR TITLE
Fix search bug

### LINKED ISSUE #769: (Priority)Search Bug
### What happened just before the problem occurred

Some backend search constraints were implemented in #630 by me which cut out some extra database queries if your search query is less than 3 characters long. 

Since then the entire UI has been updated - but if you make any query it re-renders the old UI and you can't get back to the new one:

search constraint2

Less priority - 
Was initially going to open this issue to say constraint performance could be improved on a lot by adding frontend JS constraints - because currently a query less than 3 chars long still causes a page reload. 

### Relevant URLs

https://

### PublicLab.org username

(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

### PR DESCRIPTION
**Pull request by cesswairimu**
Fixes #769 

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/mapknitter-reviewers` for help, in a comment below

### CODE REVIEW

**Comment by cesswairimu** [comment]
search

**Comment by cesswairimu** [comment]
@publiclab/mapknitter-reviewers please review

**Comment by jywarren** [comment]
Ah it was a failure with the rubocop linter!

**Comment by jywarren** [comment]
```
Inspecting 28 files
.........................W..
Offenses:
app/helpers/front_ui_helper.rb:4:5: W: Lint/UselessAssignment: Useless assignment to variable - img. Use || instead of ||=.
    img ||= "/images/yarn.png"
    ^^^
28 files inspected, 1 offense detected
```

**Comment by jywarren** [comment]
🎉 Great!!!

**Pull request merged**
