### PR TITLE
Fix Coveralls

### LINKED ISSUE #491: Environment variables not loading on travis for external PRs
Travis does not load environment variables due to security concerns, (https://docs.travis-ci.com/user/pull-requests#pull-requests-and-security-restrictions)
This is a valid security concern because anyone can send a PR that prints and exposes the env variables to the logs. 
It is however a setback for us since it restrains us from sending coverage reports to Coveralls/Codeclimate. Because of this we can't see coverage change on external prs. (This is important for us because we might want to encourage contributors to send prs with sufficient tests so that test coverage does not decrease)
For example compare https://github.com/publiclab/mapknitter/pull/467 and https://github.com/publiclab/mapknitter/pull/462 

The same issue exists for plots2 as well. Notice how a repo can't be found to send report to coveralls in this build. https://travis-ci.org/publiclab/plots2/builds/512970864#L3498
Currently only push builds are sending coverage reports to coveralls.

I can't find a good solution for this that doesn't include making the environment variables public, which should be our last resort.

### PR DESCRIPTION
**Pull request by kaustubh-nair**
Fixes #491 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hmm, is coveralls supposed to show a check here? Thanks!!

**Comment by kaustubh-nair** [comment]
@jywarren 
It will show a check once the repo token is added to `.coveralls.yml`

**Comment by jywarren** [comment]
Oh great, I remember now. Thanks!

**Comment by sashadev-sky** [comment]
closing this as we have dropped support for coveralls in favor of codecov (#543)

**Pull request closed without merging**
