### PR TITLE
Update seeds.rb

### LINKED ISSUE #612: Getting error from seeds.rb file
For the line:
https://github.com/publiclab/mapknitter/blob/1ba35931e4d24dc3854fe663a19fcce61dd4009c/db/seeds.rb#L15

I got the error that the method `login` was undefined when I ran `rake db:setup`

This code was recently merged (8 hours ago)

### PR DESCRIPTION
**Pull request by sashadev-sky**
Fixes #612 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@cesswairimu can you please advise here because this was your code originally

**Comment by cesswairimu** [comment]
Hi @sashadev-sky, thanks for the fix initially when I was running the seed file I had users from the test env. I see there was no users when doing setup. Maybe we should add fake for users.

**Comment by jywarren** [comment]
generally this is awesome. We've had issues with people doing initial
install and being confused at not seeing any maps/users. This will also
help with the local login bypass at sessions_controller#local -- as i
documented in the README recently. thank you!!!

**Comment by sashadev-sky** [comment]
@cesswairimu perfect thank you! I tested that locally and it worked so I put `.login` back and added your suggestion :)

**Comment by sashadev-sky** [comment]
@jywarren noted about the README updates. I just checked them out. 

Since we will now have 5 users in the seed file, should I update the below lines from:

```
For this to work, there will have to be a user record first. 
You can create one by running `rails console` to open a rails console, 
then entering `u = User.create({login: 'harry', email: 'potter@hogwarts.com'})`
```

to something like: 

For this to work, there has to be a user record first. A few user instances will populate from the seed file during your initial database setup for convenience. You can check this by running `rails console` to open a rails console, then entering `User.all`.

**Comment by cesswairimu** [comment]
@sashadev-sky just a thought maybe we can add this at the top of the seed file ` User.create({login: 'harry', email: 'potter@hogwarts.com'})` then we will just update Readme to use `harry` (or whatever name you choose to use). Sorry am just throwing things randomly here. Let me know what you think. Thanks

**Comment by sashadev-sky** [comment]
@cesswairimu Oh ok I see! That makes the most sense to me. 

So if I make this update, and there is this documentation for how to easily login using harry (just go to localhost:3000/local/harry), then do you think it makes sense to delete `.login` as I had done previously? 

I think it would be a little confusing for the user to be logged into a random account when they visit the page in development. It also wouldn't log them in everytime they run the rails server, just once when they seed the database, which could confuse new contributors even more.

**Comment by cesswairimu** [comment]
No, I meant you leave your changes as they are. i.e with the fake users, and add the specific user at the top.  So initially we will have 6 users after the seeds are ran. I believe we have `rake db:setup` as one of the commands during installation steps and  if a new contributor runs that, it also runs the seed file which means they have `harry` in the db as they start. Makes sense?

**Comment by cesswairimu** [comment]
My thinking is that it might be easier for them to have a user already setup rather than having to create a user from the console

**Comment by sashadev-sky** [comment]
@cesswairimu Yes I am on the same page as you! 

My concern is that, if i'm understanding correctly, having the `.login` there will make it so that the contributor will already be logged into the page under a random Faker account name as soon as they open it. I think this might be a little confusing, and since we have another solution to make it very quick to login if they would like to, we should remove this and leave it up to the user if they want to login

**Comment by sashadev-sky** [comment]
> My thinking is that it might be easier for them to have a user already setup rather than having to create a user from the console

Yes same page here too! I am just thinking about the necessity of `.login` at this point

**Comment by cesswairimu** [comment]
Aha! gotcha, the `login` was just for associating a user to a map...so that owner is not set to `anonymous`

**Comment by cesswairimu** [comment]
Sorry @sashadev-sky for the confusion I see it now..no need for the `.login` without will do it. Thanks

**Comment by sashadev-sky** [comment]
@cesswairimu I saw this message in my email: 

Sorry @sashadev-sky for the confusion I see it now..no need for the .login without will do it. Thanks

was it intentionally deleted?

**Comment by cesswairimu** [comment]
yeah, sorry, thought that could work, but it will assign the user object to the author instead of the user's name...so it will have to leave the `.login`.

**Comment by cesswairimu** [comment]
@sashadev-sky please test locally see what works and we will just go with it. Thanks

**Comment by sashadev-sky** [comment]
@cesswairimu I'm going to check if I can just log them all out after the association is formed. Will update you

**Comment by jywarren** [comment]
Hi, thanks everyone for the great collab here. Just chiming in to agree
with the README changes. Awesome!

**Comment by sashadev-sky** [comment]
@cesswairimu ok this is ready if you'd like to review! Basically I made the random accounts all basic and made two known accounts at the top, one basic and one admin. The `.login` problem was from a syntax error I think, it is fixed now.

**Comment by sashadev-sky** [comment]
@jywarren for the `README` update, I was thinking, should we just update `config/config.yml.example` to include `local: true`, and update the README `installation` section here:
```
4. Copy and configure config/config.yml from config/config.yml.example 
(for now, this is only for the [Google Maps API Key, which is optional](http://stackoverflow.com/questions/2769148/whats-the-api-key-for-in-google-maps-api-v3))
```
I think even though it says optional right now, most people would do this step anyway. So people should already have the file created, and we don't need to tell them to create it with that block under `## Logging in when running locally`. 

Then we can link the `logging in when running locally` section in the installation step, so people will be directed to it and find an explanation of the `local: true` configuration and how to use the local login route.

Right now I think this section could be easily overlooked.

**Comment by jywarren** [comment]
I had left it as an extra step to do local: true just because you do /not/
want it to go to production code. I know it's only set in development,
but... people should know it's a security risk. But ok - can we do comments
in YAML? Yeah -- let's just add a helpful comment to comment.yml reminding
people about the security risk: `# This makes a local login path in
DEVELOPMENT mode only. Do not use this configuration in production as it is
a security risk.`

How's that sound?

**Comment by sashadev-sky** [comment]
@jywarren Ok this is good to go on your confirmation!

**Comment by jywarren** [comment]
Awesome, team!!! 🙌🏽🙌🏽🙌🏽⚡⚡⚡

**Pull request merged**
