### PR TITLE
Local builds for Travis runners

### PR DESCRIPTION
**Pull request by alaxalves**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by alaxalves** [comment]
Ok guys @kaustubh-nair @jywarren, so apparently https://github.com/publiclab/mapknitter/pull/605 was not enough to completely split our environments apart. I later realized that the previously created file docker-compose.test.yml was using our default Dockerfile to create its image, and our Dockerfile has been set for production, as well as the production's default docker-compose.yml file. So by making the docker-compose.test.yml file "inherit" of the default Dockerfile was not a good call. Anyway this was causing some misleading on the builds, Codecov and such. Along with @kaustubh-nair we have decided that the best approach was using the default settings provided by Travis itself and include a job testing the builds of the docker image.

**Comment by alaxalves** [comment]
Some good news is that by setting our runners like this, we got to decrease the build time even more, something like ~2x faster. Check the Before/After:
image
https://travis-ci.org/publiclab/mapknitter/builds/542443630

image
https://travis-ci.org/publiclab/mapknitter/builds/542460131

**Comment by alaxalves** [comment]
Hey guys @kaustubh-nair @cesswairimu the functional tests have been passing in my local environment. Also, @jywarren @icarito could yall give me a hint on the Unit tests? Please check the set up I've made in travis.

**Comment by jywarren** [comment]
I see the error here: 

```
ERROR["test_should_display_export_index", #<Minitest::Reporters::Suite:0x0000000008066550 @name="ExportControllerTest">, 0.5164600869999845]
 test_should_display_export_index#ExportControllerTest (0.52s)
ActionView::Template::Error:         ActionView::Template::Error: File to import not found or unreadable: style.
        Load paths:
          /home/travis/build/publiclab/mapknitter/app/assets/images
          /home/travis/build/publiclab/mapknitter/app/assets/javascripts
          /home/travis/build/publiclab/mapknitter/app/assets/stylesheets
          /home/travis/build/publiclab/mapknitter/vendor/assets/images
          /home/travis/build/publiclab/mapknitter/vendor/assets/javascripts
          /home/travis/build/publiclab/mapknitter/vendor/assets/stylesheets
          /home/travis/build/publiclab/mapknitter/public/lib
          /home/travis/.rvm/gems/ruby-2.4.6/gems/popper_js-1.14.5/assets/javascripts
            app/assets/stylesheets/application.scss:2
            app/views/layouts/application.html.erb:16:in `_app_views_layouts_application_html_erb___2692047925648521322_22375520'
            test/functional/export_controller_test.rb:12:in `block in <class:ExportControllerTest>'
```

On this test:

https://github.com/publiclab/mapknitter/blob/3588ccd8b2510472d6aa73328fbf37f865f3f596/test/functional/export_controller_test.rb#L11-L17

But the error `  ActionView::Template::Error: File to import not found or unreadable: style.` makes me think it's a stylesheet issue? Yes, this line:

https://github.com/publiclab/mapknitter/blob/3588ccd8b2510472d6aa73328fbf37f865f3f596/app/assets/stylesheets/application.css#L18

it can't seem to find a stylesheet named "style.___" (probably `.css`). Any reason why that wouldn't be there? Is it looking for an scss or sass file and the asset pipeline is not able to read the filetype we're offering? Some need to be converted to `.css` so there could be some relation to the asset pipeline job also not completing? Though I didn't look at those logs.

**Pull request merged**
