### PR TITLE
Removed additional will_paginate call on _maps

### LINKED ISSUE #1437: Double pagination for maps on the author profile
We have two pagination bars displayed here  https://mapknitter.org/profile/warren

 Lets display just one

Screenshot from 2020-09-21 17-45-00

### PR DESCRIPTION
**Pull request by chethanagopinath**
Fixes #1437 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [X] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [X] code is in uniquely-named feature branch and has no merge conflicts 📁
* [X] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/mapknitter-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!
Screen Shot 2020-10-23 at 12 25 37 PM

### CODE REVIEW

**Comment by chethanagopinath** [comment]
@publiclab/mapknitter-reviewers Please let me know if my fix is okay. Thank you!

**Review by cesswairimu — CHANGES_REQUESTED** [review]
Thanks for opening this  @chethanagopinath  :tada:, I have noticed removing this removes the pagination at `/gallery`
I think removing on the pagination on https://github.com/publiclab/mapknitter/blob/main/app/views/users/profile.html.erb might work without breaking other pages. Could you please check.

**Comment by chethanagopinath** [comment]
@cesswairimu Sure, will check that out now :) thank you!

**Comment by chethanagopinath** [comment]
@cesswairimu I checked the gallery view and my change does indeed make the pagination there disappear, so I've made the according to what you've outlined and it works :) Thank you so much for helping me out!

**Review by cesswairimu — APPROVED** [review]
Great :tada:

**Pull request merged**
