### PR TITLE
New front ui

### PR DESCRIPTION
**Pull request by stefannibrasil**
Starting the work from #327

FYI: This is still going to be tested/made adjustments after review tomorrow.

### CODE REVIEW

**Comment by stefannibrasil** [comment]
I pushed to unstable, but I'm not sure it worked... I can't access the `/front-page` page :/

**Comment by jywarren** [comment]
Let's just push this to live, but i'll check with @icarito about the staging issue too! Thanks!

**Comment by icarito** [comment]
Hi!
I'm not sure why it failed - I just restarted the build and it worked!

The route exists but gives [an error](https://jenkins.laboratoriopublico.org/job/Mapknitter-Unstable/ws/log/):
```
Started GET "/front-page" for 190.232.232.108 at 2019-05-25 04:53:33 +0000
Processing by FrontUiController#index as HTML
  User Load (0.5ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 1596 LIMIT 1
  Map Load (0.8ms)  SELECT user_id, author, count(1) as maps_count FROM `maps` WHERE `maps`.`archived` = 0 AND (user_id != 0) GROUP BY author ORDER BY maps_count DESC
Mysql2::Error: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'mapknitter.maps.user_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by: SELECT user_id, author, count(1) as maps_count FROM `maps`  WHERE `maps`.`archived` = 0 AND (user_id != 0) GROUP BY author ORDER BY maps_count DESC
Completed 500 Internal Server Error in 3.4ms (ActiveRecord: 1.4ms)

ActiveRecord::StatementInvalid (Mysql2::Error: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'mapknitter.maps.user_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by: SELECT user_id, author, count(1) as maps_count FROM `maps`  WHERE `maps`.`archived` = 0 AND (user_id != 0) GROUP BY author ORDER BY maps_count DESC):
  app/models/map.rb:272:in `featured_authors'
  app/controllers/front_ui_controller.rb:6:in `index'


Started GET "/assets/style.css?body=1" for 190.232.232.108 at 2019-05-25 04:53:33 +0000
Served asset /style.css - 304 Not Modified (0ms)
Started GET "/assets/jquery-ujs/src/rails.js?body=1" for 190.232.232.108 at 2019-05-25 04:53:33 +0000
Served asset /jquery-ujs/src/rails.js - 304 Not Modified (0ms)
```

**Comment by icarito** [comment]
From http://mapknitter-unstable.laboratoriopublico.org/front-page

**Comment by jywarren** [comment]
Hi @cesswairimu just noting here is the new front page code! Thanks!!!

**Comment by cesswairimu** [comment]
Thanks Jeff

**Pull request merged**
