### PR TITLE
Full screen support added

### LINKED ISSUE #274: full-screen button for front page map
@sagarpreet-chadha the map is amazing!!! Let's make a button to take it full screen?

image

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

Fixes #274 !

* [x] tests pass -- `rake test`
* [x] code has been rebased on top of latest master (check if another pull request was added recently, and please rebase)
* [x] pull request is descriptively named and, if possible, multiple commits squashed if they're smaller changes

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
This looks good -- screenshot? We should probably do this for the /maps and inset map for PublicLab.org too! 

🎉

**Comment by sagarpreet-chadha** [comment]
screen shot 2018-08-02 at 11 52 02 pm
screen shot 2018-08-02 at 11 51 43 pm

**Comment by jywarren** [comment]
this looks great, let's try it out!

**Comment by jywarren** [comment]
If we bump the version number `0.x.0` for new feature, we can get this up on MapKnitter and PublicLab, but no rush as we have plenty of other upgrades to make.

**Comment by jywarren** [comment]
Oh man, sorry, i got mixed up. this is right on MapKnitter. Will publish tomorrow!

**Pull request merged**
