### PR TITLE
Revert database.yml to previous state

### PR DESCRIPTION
**Pull request by kaustubh-nair**
Fixes failing build on jenkins https://jenkins.laboratoriopublico.org/job/Mapknitter-Stable/lastFailedBuild/console
I've reverted it back to https://github.com/publiclab/mapknitter/blob/d1e801b436f47c4fe78c0a7cf9bda1503ce8a44b/config/database.yml.example
Let's see how it goes

### CODE REVIEW

**Comment by kaustubh-nair** [comment]
I've reverted to exactly the same `database.yml` that we used to previously use. Why is this failing?!? :confused: 
@alaxalves Need some help here

**Comment by kaustubh-nair** [comment]
But surprisingly `unstable` is working! 
https://jenkins.laboratoriopublico.org/job/Mapknitter-Unstable/103/

**Comment by alaxalves** [comment]
I think I know what is going on here Kaustubh, I have fixed it on Rails 5.2.3 upgrade. Just reverting database.yml wont fix our problem. Remember that we have found out that we had been running Travis for production env? So this is kinda related, out test credentials are mismatched. I'll try some stuff here.

**Comment by alaxalves** [comment]
@jywarren @sashadev-sky @kaustubh-nair Pushed this to unstable and fixed it both on Travis and Jenkins. :D

Jenkins at: https://jenkins.laboratoriopublico.org/job/Mapknitter-Unstable/109/console
Travis at: https://travis-ci.org/publiclab/mapknitter/builds/550805436?utm_source=github_status&utm_medium=notification

**Comment by jywarren** [comment]
Awesome! Perfect, shall we merge it?

**Comment by jywarren** [comment]
Ah i see you commented in Gitter. Merging then! Thanks!!

**Pull request merged**
