### PR TITLE
(WIP)Move some controller code to models

### LINKED ISSUE #304: Planning issue: expand test coverage with more thorough testing
Mapknitter repository requires a lot of unit tests, integration tests, fixtures and functional tests for each MVC pattern present in the repo along with routes explorations.
So @jywarren we can discuss testing in this issue.
Refer #300

### PR DESCRIPTION
**Pull request by cesswairimu**
Fixes part of #527 and code some cleanup

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by cesswairimu** [comment]
@publiclab/reviewers  please review, PR getting too big will push the rest of the changes to a different branch

**Comment by jywarren** [comment]
Hi Cess! Sorry this bot is a bit much, huh? We can turn it off... I thought
it would make a maximum of five suggestions. What do you think?

**Comment by cesswairimu** [comment]
Yeah @jywarren yeah I think it makes five suggestions for each commit. Yeah maybe we can turn it off someone might miss a reviwers comment if it gets this long

**Comment by jywarren** [comment]
Ok! I'll turn it off now!

**Comment by jywarren** [comment]
I changed it to 5 max per PR, but we can turn it down even more! Let's see. 

Also do you like this kind of coverage reporting? https://github.com/publiclab/image-sequencer/pull/1016

**Comment by jywarren** [comment]
Also, I thought it was going to stop giving comments on code you didn't add, after the first approval but maybe that didn't happen, or maybe your refactor is just much bigger. Tell me if this is ready to merge!

**Comment by cesswairimu** [comment]
> I changed it to 5 max per PR, but we can turn it down even more! Let's see.
> 
> Also do you like this kind of coverage reporting? [publiclab/image-sequencer#1016](https://github.com/publiclab/image-sequencer/pull/1016)

Wow this looks dope, Yeah I love it

**Comment by cesswairimu** [comment]
This is ready to merge just rebased it

**Comment by jywarren** [comment]
Awesome!!!

**Comment by kaustubh-nair** [comment]
Hey @cesswairimu just a heads up
Can you please mention the issue you are working on before starting the work?
I had already fixed some rubocop issues in https://github.com/publiclab/mapknitter/pull/534
This was a really small pull request so it isn't much of a problem, but it might be useful to coordinate if we are working on something big
Thanks! :)

**Comment by cesswairimu** [comment]
Am sorry @kaustubh-nair for any inconvenience, will be doing so..on that note I am still working on #527 refactoring the controllers and moving some controller code to models. sorry again

**Comment by kaustubh-nair** [comment]
It's okay Cess, not really a big deal :smile:
Thanks for the update :)

**Pull request merged**
