### PR TITLE
Bump LDI

### PR DESCRIPTION
**Pull request by sashadev-sky**
References #124  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@jywarren do you think this PR sufficiently closes the discussion in https://github.com/publiclab/mapknitter/issues/124?

**Comment by jywarren** [comment]
Yep!!

**Comment by jywarren** [comment]
Awesome.

**Comment by jywarren** [comment]
Looking good! http://mapknitter-stable.laboratoriopublico.org/maps/test--226

**Comment by jywarren** [comment]
However the lock icons seem missing? And the menu formatting is a little off, the "stem" is detached. But otherwise great!!
Screenshot_20190509-112829

**Comment by sashadev-sky** [comment]
@jywarren how do I recreate this scenario? Whenever I click on a map it redirects me to the production site, which still has the old interface

**Comment by sashadev-sky** [comment]
Weirdly enough I think I was on the production site yesterday on my cellphone and noticed an issue with the lock handles, but now it is working fine. Did you revert any changes because I guess that would tell us where to start looking into this

**Comment by jywarren** [comment]
I wonder if it was a caching issue as I believe it was working for us as we
were trying to do the big publication just now. (see gitter chatroom for
latest updates on that!) Calling it a night now! Thanks!

**Comment by sashadev-sky** [comment]
Good to hear!

**Pull request merged**
