### PR TITLE
 Send patch for new LEL library feature . #282 

### LINKED ISSUE #282: Send patch for new LEL library feature .
Spinner.js script's have to be added . Sending PR today !

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
Fixes #282 !

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- `rake test`
* [ ] code has been rebased on top of latest master (check if another pull request was added recently, and please rebase)
* [ ] pull request is descriptively named and, if possible, multiple commits squashed if they're smaller changes

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hmm, what's the error here?

**Comment by sagarpreet-chadha** [comment]
screenshot 2018-11-24 at 4 19 22 pm

**Comment by sagarpreet-chadha** [comment]
Resolved now 👍  !

**Comment by jywarren** [comment]
Awesome!!!

**Pull request merged**
