### PR TITLE
Lower priority for GDAL processes

### PR DESCRIPTION
**Pull request by icarito**

### CODE REVIEW

**Comment by jywarren** [comment]
Great - have you tested this line locally, and confirmed that nice is available on the server?

**Comment by icarito** [comment]
Nice is a standard utility, it's in the server for sure. But I haven't tested it because I haven't setup a testing or dev environment and I'd rather not experiment on production service.

**Comment by jywarren** [comment]
So shall we try it out on a cloud9 instance, which is Ubuntu?

**Comment by icarito** [comment]
Yes that sounds great.

**Comment by jywarren** [comment]
OK, i'm inviting you to my mapknitter build. It's not 100% standard, but
should enable some experimentation.

**Comment by icarito** [comment]
I haven't been able to test this but I think the simplest solution of all will be to write a small wrapper around convert script.

**Comment by jywarren** [comment]
I believe the proposed change for gdal will also affect convert processes.
We run everything through the same pipeline if I recall correctly.

**Comment by icarito** [comment]
I've manually been renicing processes and can confirm this alleviates the cpu exhaustion issue. There is an increase in activity tonight so I'm tempted to apply this as hotfix.

**Comment by icarito** [comment]
Deployed in production as hotfix.

**Comment by jywarren** [comment]
Cool - if it runs, let's just merge it in. Shall I?

**Comment by icarito** [comment]
Sure!
I'd do it but... "Only those with write access to this repository can merge pull requests."

**Comment by jywarren** [comment]
Done. I'll run tests and merge to stable too.

**Pull request merged**
