### PR TITLE
(WIP)Add ".tiff" as content upload type

### LINKED ISSUE #206: Image Upload Problem
Will mapknitter accept geotiff (extension .tif)?  It starts the upload and then after a bit only the spinning circle is present.  All the other information about the upload progress disappears.  The file size is only 3.057MB.  File was attached to email to mailing list.  Tif files do not attach to github issues.

### PR DESCRIPTION
**Pull request by cesswairimu**
Fixes #206 

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by jywarren** [comment]
Wow cool! Are you able to confirm manually that a Tiff can be uploaded?
Thanks Cess!

**Comment by jywarren** [comment]
Actually this should be all good; i'm wondering if a .tiff can be exported in `mapknitter-exporter`, and we can test that later!

**Comment by cesswairimu** [comment]
Hey @jywarren, The upload is working fine but placing the image on the map fails. The js error returned is "No compass found" I narrowed it down to this https://github.com/publiclab/mapknitter/blob/main/app/assets/javascripts/mapknitter/Map.js#L300-L310 but not sure why this is happening. Any ideas?

**Comment by jywarren** [comment]
ahhh, ok, we're going to be updating that function soon and taking it out
of the mapknitter code. It's looking for gps compass data in a jpg image.
Do you think you can coordinate with @rexagod to remove this from the
mapknitter codebase as @rexagod is working on reimplementing it as part of
Leaflet.DistortableImage? We can even just comment out the line where the
function is called, for now. Thanks!

**Comment by cesswairimu** [comment]
Sure, I will comment if for now and work with @rexagod on removing the function. thanks @jywarren

**Comment by jywarren** [comment]
Just feel free to ping me if this should be merged! Also, @cesswairimu I would be fine sharing merge rights on MapKnitter with you if you're comfortable with it. You can (should?) still feel free to ask for reviews from others before merging, but it may speed the process a bit. Thanks!

**Comment by rexagod** [comment]
Always excited to collab with Cess! 🚀 😄 

@cesswairimu I can't push to this branch. Can you add me as a collaborator to your fork of this repo?

@jywarren I made the requested changes to the [EXIF PR](https://github.com/publiclab/Leaflet.DistortableImage/pull/169) a week ago, but I do understand that you're very busy these days so can you please check it out whenever you have some time? Thanks!

**Comment by rexagod** [comment]
Also, I added a new comment to the  [feature detection issue](https://github.com/publiclab/Leaflet.DistortableImage/issues/110#issuecomment-488421626) but no rush with this, and thank you @jywarren for mentioning me here!

**Comment by cesswairimu** [comment]
Thanks @rexagod :smiley: , I just sent an invite

**Comment by jywarren** [comment]
ah cool thanks @rexagod, I'll check it out, sorry i missed it!

**Comment by cesswairimu** [comment]
Just noting I tried commenting out the function part, but that did not fix the 'place' still looking into it though.

**Comment by rexagod** [comment]
Cess can you get on Gitter right now? I need to clarify a few things.

**Comment by rexagod** [comment]
>Just noting I tried commenting out the function part, but that did not fix the 'place' still looking into it though.

Cess, just to confirm, did you do anything other than removing both fns and commenting out their calls (i.e., anything other than the diff below)?

```
@@ -237,105 +237,6 @@ 
-  geocodeImageFromId: function(dom_id,id,url) {
-    window.mapKnitter.geocodeImage(
-      $(dom_id)[0],
-      function(lat,lng,id,angle,altitude) {
-        /* Display button to place this image with GPS tags. */
-        $('.add-image-gps-'+id).attr('data-lat',lat);
-        $('.add-image-gps-'+id).attr('data-lng',lng);
-        if (angle) $('.add-image-gps-'+id).attr('data-angle',angle);
-        if (altitude) $('.add-image-gps-'+id).attr('data-altitude',altitude);
-        $('.add-image-gps-'+id).show();
-        $('.add-image-gps-'+id).on('click',function() {
-          $('.add-image-'+id).hide();
-          $('#uploadModal').modal('hide');
-          window.mapKnitter._map.setZoom(18);
-          window.mapKnitter._map.setView(
-            [$(this).attr('data-lat'),
-             $(this).attr('data-lng')]);
-          var angle = $(this).attr('data-angle') || 0;
-          var altitude = $(this).attr('data-altitude') || 0;
-          img = window.mapKnitter.addImage(url,
-                                     id,
-                                     $(this).attr('data-lat'),
-                                     $(this).attr('data-lng'),
-                                     angle,
-                                     altitude);
-          $('#warpable-'+id+' a').hide();
-        })
-      },
-      id
-    )
-  },
-
-  /*
-   * Accepts an image element, and executes given function with 
-   * params as: function(lat,lng) {}
-   * Adapting from: 
-    https://github.com/publiclab/mapknitter/blob/6e88c7725d3c013f402526289e806b8be4fcc23c/public/cartagen/cartagen.js#L9378
-  */
-  geocodeImage: function(img,fn,id) {
-    EXIF.getData(img, function() {
-      var GPS = EXIF.getAllTags(img)
- 
-      /* If the lat/lng is available. */
-      if (typeof GPS["GPSLatitude"] !== 'undefined' && typeof GPS["GPSLongitude"] !== 'undefined'){
-
-        // sadly, encoded in [degrees,minutes,seconds] 
-        var lat = (GPS["GPSLatitude"][0]) + 
-                  (GPS["GPSLatitude"][1]/60) + 
-                  (GPS["GPSLatitude"][2]/3600);
-        var lng = (GPS["GPSLongitude"][0]) + 
-                  (GPS["GPSLongitude"][1]/60) + 
-                  (GPS["GPSLongitude"][2]/3600);
-
-        if (GPS["GPSLatitudeRef"] != "N")  lat = lat*-1
-        if (GPS["GPSLongitudeRef"] == "W") lng = lng*-1
-      }
-
-      // Attempt to use GPS compass heading; will require 
-      // some trig to calc corner points, which you can find below:
-
-      var angle = 0; 
-      // "T" refers to "True north", so -90.
-      if (GPS["GPSImgDirectionRef"] == "T")
-        angle = (Math.PI / 180) * (GPS.GPSImgDirection["numerator"]/GPS.GPSImgDirection["denominator"] - 90);
-      // "M" refers to "Magnetic north"
-      else if (GPS["GPSImgDirectionRef"] == "M")
-        angle = (Math.PI / 180) * (GPS.GPSImgDirection["numerator"]/GPS.GPSImgDirection["denominator"] - 90);
-      else
-        console.log("No compass data found");
-
-      console.log("Orientation:",GPS["Orientation"]) 
-
-      /* If there is orientation data -- i.e. landscape/portrait etc */
-      if (GPS["Orientation"] == 6) { //CCW
-        angle += (Math.PI / 180) * -90
-      } else if (GPS["Orientation"] == 8) { //CW
-        angle += (Math.PI / 180) * 90
-      } else if (GPS["Orientation"] == 3) { //180
-        angle += (Math.PI / 180) * 180
-      }
- 
-      /* If there is altitude data */
-      if (typeof GPS["GPSAltitude"] !== 'undefined' && typeof GPS["GPSAltitudeRef"] !== 'undefined'){
-        // Attempt to use GPS altitude:
-        // (may eventually need to find EXIF field of view for correction)
-        if (typeof GPS.GPSAltitude !== 'undefined' && 
-            typeof GPS.GPSAltitudeRef !== 'undefined') {
-          altitude = (GPS.GPSAltitude["numerator"]/GPS.GPSAltitude["denominator"]+GPS.GPSAltitudeRef);
-        } else {
-          altitude = 0; // none
-        }
-      } 
-
-      /* only execute callback if lat (and by 
-       * implication lng) exists */
-      if (lat) fn(lat,lng,id,angle,altitude);
-    }); 
-  },
-
@@ -23,7 +23,7 @@
               <!-- <a href="">Re-place</a>  -->
               <script>
                 jQuery(document).ready(function($) {
-                  window.mapKnitter.geocodeImageFromId('#warpable-img-<%= warpable.id %>',<%= warpable.id %>,'<%= warpable.image.url(:medium) %>');
+                  # window.mapKnitter.geocodeImageFromId('#warpable-img-<%= warpable.id %>',<%= warpable.id %>,'<%= warpable.image.url(:medium) %>');
                 })
               </script>
             <% end %>
@@ -94,7 +94,7 @@
                       <script>
                         $('#warpable-{%= file.id %} [rel=tooltip]').tooltip();
                         $("#warpable-img-preview-"+{%= file.id %}).on('load', function() {
-                          window.mapKnitter.geocodeImageFromId("#warpable-img-preview-"+{%= file.id %},{%= file.id %},'{%= file.url %}'); 
+                          # window.mapKnitter.geocodeImageFromId("#warpable-img-preview-"+{%= file.id %},{%= file.id %},'{%= file.url %}'); 
                         })
                     {%# "</sc"+"ript>" %}
                   </td>
```

**Comment by cesswairimu** [comment]
Nope, I just commented them out as :point_up: and removed them in the template calls

**Comment by cesswairimu** [comment]
This PR has been open for a long time and no activity/ reviews requested has not been addressed. We understand you might be busy and engaged on other things. I am closing this for now...please  feel free to reopen if you get some time and would like to finish this. Rem to check if its still available before you reopen. Thanks :laughing: :laughing:

**Comment by cesswairimu** [comment]
talk about saved replies to your own  PR :rofl:

**Comment by SidharthBansal** [comment]
Well done

**Pull request closed without merging**
