### PR TITLE
Added leaflet-hash library

### LINKED ISSUE #419: change layer not in local machine
### What happened just before the problem occurred
we can see there is no an option for change layer in localhost but
**In localhost:**
pub6
**It must be like in Production:**
pub7

### Relevant URLs

https://localhost:3000

### PublicLab.org username
singhav
(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

### PR DESCRIPTION
**Pull request by igniteeng000**
Fixes #419 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkboxe write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by igniteeng000** [comment]
@publiclab/reviewers @jywarren please review.

**Comment by avsingh999** [comment]
@igniteeng000 Can you please post a Screenshot/gif.
thanks : )

**Comment by igniteeng000** [comment]
@jywarren please take a look. Thanks.

**Comment by sashadev-sky** [comment]
My view looks strange but one thing I do have is the layers button already

@avsingh999 can you check if your issue is still valid as you posted it 20 days ago

mappp

**Comment by igniteeng000** [comment]
yeah this issues are valid because leaflet-hash libraries are not installed by bower install.

**Comment by avsingh999** [comment]
@sashadev-sky It's Valid for me. But I think @igniteeng000 also right.
: )

**Comment by sashadev-sky** [comment]
@igniteeng000 Closing this as it is no longer relevant as of your PR here: https://github.com/publiclab/mapknitter/pull/516

Thank you for your work on this!

**Pull request closed without merging**
