### PR TITLE
Test asset compilation on travis

### PR DESCRIPTION
**Pull request by kaustubh-nair**
Checking if `rake assets:precompile` works correctly on travis since we've switched to Rails 4

### CODE REVIEW

**Comment by kaustubh-nair** [comment]
Hey @alaxalves, there's a problem with the production environment here. Can you have a look?
Thanks

**Comment by alaxalves** [comment]
> Hey @alaxalves, there's a problem with the production environment here. Can you have a look?
> Thanks

https://github.com/publiclab/mapknitter/pull/725 Solves it.

**Comment by kaustubh-nair** [comment]
> > Hey @alaxalves, there's a problem with the production environment here. Can you have a look?
> > Thanks
> 
> #725 Solves it.

Okay let me try push those commits here

**Comment by kaustubh-nair** [comment]
The build is still failing @alaxalves 
But I was thinking.. why do we need to test this on travis?
We'll be doing it on jenkins anyway right?

**Comment by alaxalves** [comment]
> The build is still failing @alaxalves
> But I was thinking.. why do we need to test this on travis?
> We'll be doing it on jenkins anyway right?

The issue now is related to the assets, not the builds, BTW this is going well on https://github.com/publiclab/mapknitter/pull/685. I think is related to the newer Yarn setup and asset related gems upgrade.
I think it's necessary having this job, because it makes clearer and faster to identify when an asset is deprecated and such. But let's hear from @sashadev-sky too.

**Comment by alaxalves** [comment]
> The build is still failing @alaxalves
> But I was thinking.. why do we need to test this on travis?
> We'll be doing it on jenkins anyway right?

BTW the build is failing now because of the single asset job. It wasn't running any test previously.

**Comment by alaxalves** [comment]
I don't this MR is needed since it's already fixed here -> #685

**Comment by kaustubh-nair** [comment]
There might be an issue with database.yml on jenkins with that pull. That I why I opened a sperate pull request

On Jun 28, 2019 3:04 AM, Álax de Carvalho Alves <notifications@github.com> wrote:

I don't this MR is needed since it's already fixed here -> #685<https://github.com/publiclab/mapknitter/pull/685>

**Comment by kaustubh-nair** [comment]
Fixed in rails 5

**Pull request closed without merging**
