### PR TITLE
Fixing cache path in between builds

### PR DESCRIPTION
**Pull request by alaxalves**
Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/mapknitter-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by alaxalves** [comment]
Pushing this to main already since builds are taking too long. 

**Before caching:**
image

**After caching:**
image

**Comment by jywarren** [comment]
Will this help us with #791 ? Looks great, the speedup is amazing!

**Comment by jywarren** [comment]
Is this ready for merge, in any case? Thank you!

**Comment by alaxalves** [comment]
> Is this ready for merge, in any case? Thank you!

Yes it it's, but it has nothing to do with #791. #791 I'm working at #803

**Comment by jywarren** [comment]
🎉

**Pull request merged**
