### PR TITLE
improve toggle sidebar

### PR DESCRIPTION
**Pull request by avsingh999**
References \#446 (\<=== Add issue number here)

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [ ] code has been rebased on top of latest master (check if another pull request was added recently, and please rebase)
* [x] pull request is descriptively named and, if possible, multiple commits squashed if they're smaller changes

Thanks!

### CODE REVIEW

**Comment by avsingh999** [comment]
@jywarren @SidharthBansal @gauravano please review
pub11

**Comment by jywarren** [comment]
Oops, can you remove passenger.3001.pid and passenger.3001.pid.lock? Then this is good to merge, thanks so much!!!

**Comment by avsingh999** [comment]
@jywarren @gauravano @SidharthBansal please review me.
thanks ; )

**Comment by gauravano** [comment]
Hi @avsingh999, please remove the merge conflicts here. Thanks!

**Comment by sashadev-sky** [comment]
@avsingh999 @gauravano @jywarren I pulled this implementation and it was not working for me. @avsingh999 Perhaps your rebase might have pulled in some changes that were not compatible with your code. I didn't look into this too much because I figured there was a much simpler way to go about this anyway, and I committed that here.

@avsingh999 let me know if this is fine with you! Always happy to revert if you have any objections.

**Comment by sashadev-sky** [comment]
@avsingh999 @gauravano @jywarren my view after this rebase and my commit looks just like the one @avsingh999 posted a gif of above. 

Before my commit this is what I was seeing:
chevron-toggle

**Comment by jywarren** [comment]
👍

**Pull request merged**
