### PR TITLE
Icon added

### LINKED ISSUE #538: Add font awesome icon
**Description**
Add a font-awesome-icon to ```Ask a question``` to make it consistent with the other two.
Selection_135

### PR DESCRIPTION
**Pull request by divyabaid16**
Fixes #538  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

Before:
Selection_135

After:
Selection_136

[//]: # (To mark checkbox write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

Thanks!

### CODE REVIEW

**Comment by divyabaid16** [comment]
@gauravano @jywarren I don't know why the code travis-ci is failing. Can you tell me?

**Comment by kaustubh-nair** [comment]
It looks like the keyserver is still not reliable
Lets try rebuilding..

**Comment by kaustubh-nair** [comment]
@divyabaid16 Looks like it worked :tada:

**Comment by kaustubh-nair** [comment]
@divyabaid16 The build is passing now :tada:

**Comment by kaustubh-nair** [comment]
@icarito the build was failing for this pull request again https://travis-ci.org/publiclab/mapknitter/builds/520125772?utm_source=github_status&utm_medium=notification
I don't know if we should be concerned about this or not, but I thought I'd let you know!
Thanks

**Comment by divyabaid16** [comment]
@publiclab/infrastructure any reviews for this?
Thanks!

**Comment by sashadev-sky** [comment]
@divyabaid16 this looks great thank you!

**Comment by sashadev-sky** [comment]
(just for documentation) here is what the final UI looked like with @divyabaid16's changes after rebase:
Screen Shot 2019-05-12 at 4 40 04 AM

**Pull request merged**
