### PR TITLE
New front page design

### LINKED ISSUE #327: MapKnitter Front Page UI discussion
Arriving at the front of MapKnitter, we see a map of maps and a list of recently started maps, and some recent authors. 

image

We could do better! I'm brainstorming, i think there may be 2 issues - a true front page that really welcomes and shows how these maps can be made -- with illustrations of balloon mapping kits, say. 

Second, region-specific pages that show maps, mappers, projects, and more from the Public Lab community for a specific region. I'm [brainstorming](https://docs.google.com/presentation/d/1TCZoTfuhamRVrUak8aDgqJAwSgyhRtZg2Pgacl2_4zc/edit#slide=id.g4e2261b4b2_0_0) something like:

image

Note that this integrates more layers from https://github.com/publiclab/leaflet-environmental-layers/, as well as embedded content from PublicLab.org.

### PR DESCRIPTION
**Pull request by cesswairimu**
Fixes #327 
_Adding a little checklist from the issue_
* [x] featured mappers might use the last image they uploaded
* [x] let's replace "waterproof mini camera" with this: https://store.publiclab.org/products/raspberry-pi-camera
--------------------------------------------------------------------------------------------------------------- 

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/mapknitter-reviewers` for help, in a comment below

### CODE REVIEW

**Comment by jywarren** [comment]
Cool - can you share a screenshot? Thanks @cesswairimu !

**Comment by cesswairimu** [comment]
Sure @jywarren 
screencapture-localhost-3000-front-page-2019-06-24-22_50_14

**Comment by jywarren** [comment]
Wow this is looking good! Can we get it to prompt you for your location in
JavaScript geocoding API (this can be in a follow-up) and to re-center the
map if you accept?
https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API

**Comment by jywarren** [comment]
Otherwise is this good to merge? Thank you!

**Comment by cesswairimu** [comment]
Locally its working pushing to unstable to confirm this works there as well.
locate

**Comment by cesswairimu** [comment]
Hey Jeff, the 'prompt position' fix for prod is taking taking longer. we can merge this for now, I will open another PR for making the location prompt appear in production and the nearby places implementation. Thanks

**Comment by cesswairimu** [comment]
Also could it be that we turn off/block pop up notifications in unstable? Thanks

**Comment by cesswairimu** [comment]
Actually came across this https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only It blocks Geolocation for website affects any page currently using the Geolocation API from pages served over HTTP (non-secure). And unstable uses `http` so maybe that might be why :thinking:

**Comment by jywarren** [comment]
Ah! That must be it! You can likely test it locally... or if it fails
perhaps we just ensure it fails gracefully?

**Comment by cesswairimu** [comment]
Yeah I did, see gif above :point_up:

**Comment by jywarren** [comment]
Oh awesome! Ready for merge then? Great work!

**Comment by jywarren** [comment]
What do you think about adding an iframe with balloon mapping questions from publiclab.org/balloon-mapping?

**Comment by jywarren** [comment]
You can generate it by pressing the "code" button in lower right of any inline grid:

```
<iframe style="border:none;" width="100%" height="900px" src="//publiclab.org/embed/grid/question:balloon-mapping"></iframe>
```

**Comment by jywarren** [comment]
We could feature a couple grids at the very bottom?

**Comment by jywarren** [comment]
Maybe questions and activities for balloon mapping?

**Comment by cesswairimu** [comment]
Sounds good, on it. Thanks

**Comment by cesswairimu** [comment]
Wow! I have never used iframes before these are super dope. Thanks @jywarren. How does this :point_down: look or is it better to have the as separate instead of side by side?
screencapture-localhost-3000-front-page-2019-06-26-16_28_49

**Comment by jywarren** [comment]
Hey, these look great!!! Can you look at the failing test, and we can merge this? I might do a round of small CSS tweaks for spacing and such once it's merged. Thanks a lot, Cess!

**Comment by jywarren** [comment]
Actually, where does the link to "more people and maps" go? Should we have some kind of listing page that's a bit like the current front page that it leads to?

**Comment by cesswairimu** [comment]
Thanks Jeff, that links to this page
screencapture-localhost-3000-mappers-2019-06-27-16_22_16

**Comment by cesswairimu** [comment]
Removed some place below
screencapture-localhost-3000-front-page-2019-06-27-16_42_29

**Comment by jywarren** [comment]
OK I'm merging this! Let's brainstorm any next steps. I'd like to maybe make some listing of "all maps" as we have on the old front page, maybe on that 2nd page? Paginated, so you can browse back on old maps? 

I'll do some styling tweaks to this. How does it render on mobile, do we need to worry about that? 

Thanks @cesswairimu !!!

**Comment by cesswairimu** [comment]
Thanks @jywarren .My bad forgot to check mobile view..checking that and will fix if anything that breaks. Will work on the "all maps" page..Any suggestions on what we should call that page?

**Comment by jywarren** [comment]
We could call it the gallery?

**Comment by cesswairimu** [comment]
Nice!!!

**Pull request merged**
