### PR TITLE
Add codeclimate.yml

### LINKED ISSUE #514: Set up codeclimate
I'm thinking of setting up codeclimate for code review. This will help us fix linting and other stuff like enforcing the ruby style guide.

### PR DESCRIPTION
**Pull request by kaustubh-nair**
Fixes #514  
Make sure you have Pull request status updates and webhooks turned on in the codeclimate settings page for the repo
Thanks!

### CODE REVIEW

**Comment by kaustubh-nair** [comment]
@jywarren I didn't integrate test coverage with travis since coveralls already does this.(supposed to do this. Until #491 is fixed)

**Comment by jywarren** [comment]
Couple things here, i noticed CodeClimate had the default branch set to `master` so I changed it to `main`. 

I also turned on PR status updates but the webhooks isn't turning on -- i press "Install" but it still shows the "Install" button, unlike the PR status updates.

**Comment by jywarren** [comment]
Hmm, i can't seem to get it to turn on. Should I merge this anyways?

**Comment by kaustubh-nair** [comment]
Ah the webhooks button has a bug. It shows "install" after webhooks gets installed successfully. So I think that's fine!

**Comment by jywarren** [comment]
Ok then!!!

**Comment by jywarren** [comment]
Great work here!!!

**Comment by kaustubh-nair** [comment]
@jywarren Most of the [issues on codeclimate](https://codeclimate.com/github/publiclab/mapknitter/issues?category%5B%5D=style&page=2&status%5B%5D=&status%5B%5D=open&status%5B%5D=confirmed#) are rubocop style offences(2000/2300) 
I can break these up in small parts and create a lot of FTO issues. Should I proceed with this?

**Comment by gauravano** [comment]
hey @kaustubh-nair, if you can open FTOs for those codeclimate issues that'd be great. Thank you!

**Comment by kaustubh-nair** [comment]
@gauravano Most of them are refactoring issues due to too many lines of code. I think that will be too much for a first timer? Or will it not?

**Comment by gauravano** [comment]
Hmm, it depends on how good codeclimate describes the solution. Sometimes, their solution is good and sometimes not. But, I have also dropped a word in https://github.com/publiclab/mapknitter/issues/533 so maybe we can use those for generating FTOs and yeah, we have to do the effort.

**Pull request merged**
