### PR TITLE
update codenvy install script and readme

### LINKED ISSUE #654: Cloud Setup - add Codenvy
**Codenvy** - workspaces are disabled as of tomorrow so the whole **AWS** section will have to be removed and replaced with Codenvy.

### PR DESCRIPTION
**Pull request by sashadev-sky**
Fixes #654  (<=== Add issue number here)

- also addresses `yarn install` issue in https://github.com/publiclab/plots2/issues/5622
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/mapknitter-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!
=================

Changes:
- [x] `gem 'tzinfo-data'` added as recommended by an article linked during Codenvy installation to resolve my installation problem: https://github.com/tzinfo/tzinfo/wiki/Resolving-TZInfo::DataSourceNotFound-Errors
- [x] Node needs to be updated - https://github.com/yarnpkg/yarn/issues/6914#issuecomment-454124927

Pending:
- [ ] Get rails server to resolve to URL that works

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@jywarren @kaustubh-nair @alaxalves @gauravano

**Comment by sashadev-sky** [comment]
This fixes the `yarn install` issue described in publiclab/plots2#5622. Its the same thing for MapKnitter. The installation and setup seem good to go but the output URL is `http://0.0.0.0:3000/` which just leads to "site cant be reached". I played around with `rails s` commands updating the port, etc. localhost:3000 doesnt work either

**Comment by sashadev-sky** [comment]
nevermind got the whole thing working and updated the docs!

**Comment by jywarren** [comment]
Awesome work!!!

**Pull request merged**
