### PR TITLE
Show navbar hide sidebar

### LINKED ISSUE #523: navbar not showing  when click on toggle side bar button
### What happened just before the problem occurred

pub71

### Relevant URLs

https://

### PublicLab.org username

(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

### PR DESCRIPTION
**Pull request by sashadev-sky**
Fixes #523  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sashadev-sky** [comment]
show-hide

Note that before the sidebar went under the map which looked a little strange, but I think this is due to extra space being there, not the sidebar taking up space because `display: none` removes it from the flow of the document.

**Comment by sashadev-sky** [comment]
also was just looking at a view of another users map and it looks like this: 
show-hide2
(Is this an intentional difference? / which is preferred? Note that the 1st gif is my localhost view and the 2nd one is the production site because it redirects there)

**Comment by sashadev-sky** [comment]
@publiclab/reviewers @jywarren

**Comment by jywarren** [comment]
Oh hmm, I guess I would defer to @stefannibrasil on this?

**Comment by stefannibrasil** [comment]
I think that it would be best to have just one navbar (on top)? I had removed from the /maps page, I think... it gives more space to the form

**Comment by sashadev-sky** [comment]
@stefannibrasil cool i'm on board with that! Did you want to maybe make a commit to this PR to update this like you did the other page? I can also look into it if you're busy with other issues

**Comment by stefannibrasil** [comment]
yeah, I'm a little behind with my main work on mapknitter now, if you could take this, it would be nice! :v

**Comment by sashadev-sky** [comment]
@stefannibrasil yeah you're totally right that two nav bars is unnecessary. No problem, I will get on it!Just going to want your review after :)

**Comment by sashadev-sky** [comment]
@stefannibrasil @jywarren I never got to this but circling back now. The UI has been updated (already in production too) so that the sidebar does not have its own navbar:

sidebar

I don't think this looks bad either, so I will proceed to just make sure the navbar disappearing is fixed.

**Comment by sashadev-sky** [comment]
@jywarren @stefannibrasil Updated:
sidebar2

**Comment by sashadev-sky** [comment]
@publiclab/mapknitter-reviewers

**Comment by stefannibrasil** [comment]
this looks awesome :tada: :shipit:

**Comment by jywarren** [comment]
Awesome!!!! Great work!

**Comment by CoderJolly** [comment]
> @jywarren @stefannibrasil Updated:
> sidebar2

Its great 🎉

**Pull request merged**
