### PR TITLE
Passing CSRF token from frontend

### LINKED ISSUE #1251: Archive/spam action is not working
From https://mapknitter.org/gallery, the "ban" buttons leading to https://mapknitter.org/map/archive/newnew-c2f02200-abfd-45e7-a1a9-d2b56f451cb8 show a 404 error. 

(Note that the -permenant- trash button is now added so this is no longer critical)

image

Can't find a Sentry error but i believe the route may be incorrectly set up:

https://github.com/publiclab/mapknitter/blob/8e20d25ffd975a1f2e769a8730cc2591b24da081/config/routes.rb#L80-L82

Noting also we're adding a "delete" button next to the archive/spam button as a short-term fix:

### PR DESCRIPTION
**Pull request by gauravano**
Fixes #1251 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/mapknitter-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by gauravano** [comment]
We are not passing CSRF auth token from application layout due to which the request is failing in backend for many controller actions. This will fix all of them wherever we use default `application.html.erb` as layout.

**Comment by gauravano** [comment]
Aug-09-2020 02-52-48

**Comment by gauravano** [comment]
@sagarpreet-chadha in our case it would be sent as request parameter (default way). But, some people also configure it to send via Http header. 

This is the blog which deep dive into the CSRF - https://medium.com/rubyinside/a-deep-dive-into-csrf-protection-in-rails-19fa0a42c0ef. It's a good read :)

**Comment by cesswairimu** [comment]
Wow great..Thanks @gauravano for fixing this and thanks @sagarpreet-chadha for the review :tada:  :tada: 

Just read the blog, great read.. thanks  for sharing

**Comment by sagarpreet-chadha** [comment]
Awesome 🎉

**Comment by jywarren** [comment]
Wow, great catch, and I almost missed it! Great to have your help on this obscure issue @gauravano !!!!

**Pull request merged**
