### PR TITLE
Homepage button

### LINKED ISSUE #1174: Homepage modal buttons not scaled
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### :fire: Problem

Screenshot_20191225_171442

Screenshot_20191225_171519

On mobile phone and tablets, buttons are not of the same height.
It results in bad UI/UX and it should be fixed.

### 🚩 Solution

Screenshot_20191225_171912

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Open** the file ./mapknitter/app/views/front_ui/index.erb

- Line 55 -> add inline styles to paragraph
```html
<p style="display:flex;justify-content:space-around;"><i style="color:#aaa;">A Community Atlas hosted by <a href="https://publiclab.org">PublicLab</a></i></p>
```

- Line 64 -> add an inline style to the anchor tag
```html
<a class="btn btn-primary btn-lg" style="display:flex;align-items:center;justify-content:center;" href="" data-toggle="collapse" data-target="#anonymous-map">
```

- Line 66 -> add margin-left to inline styles
```html
<i class="fa fa-plus fa-fw" style="font-size:12px;color:white;margin-left:2%;"></i>
```

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### LINKED ISSUE #1637: Responsive error for "Getting a map kit" button
### Relevant URLs
https://mapknitter.org

### Problem
**The view of the "Getting a map kit" button layout is not changing its state according to the screen resolution.**

Before

### PR DESCRIPTION
**Pull request by singhavs**
Fixes #1637 & Fixes #1174    (<=== Add issue number here)

Before--> 

ezgif com-gif-maker

After-->

ezgif com-gif-maker(1)

[//]: # (To mark checkbox write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/mapknitter-reviewers` for help, in a comment below

### CODE REVIEW

**Comment by asaayushisingh** [comment]
Hey! @cesswairimu  Kindly review this PR. Thank You!

**Review by cesswairimu — CHANGES_REQUESTED** [review]
Hi @asaayushisingh, looks good :heart: . Just wondering is there a way we could have the same width for the two buttons. What do you think? Thanks

**Comment by asaayushisingh** [comment]
> Hi @asaayushisingh, looks good ❤️ . Just wondering is there a way we could have the same width for the two buttons. What do you think? Thanks

@cesswairimu  Yes, We can have the same width by decreasing the font size of the "Getting a Map Kit" button but then it will not look good. What do you think? 🤔

**Comment by asaayushisingh** [comment]
> > Hi @asaayushisingh, looks good ❤️ . Just wondering is there a way we could have the same width for the two buttons. What do you think? Thanks
> 
> @cesswairimu Yes, We can have the same width by making the width of the both buttons constant,




https://user-images.githubusercontent.com/67657066/163533853-b3ebda00-f5ce-4bcc-ae0f-18f4865a4a3a.mp4







@cesswairimu  Want your feedback on it. I tried to change it. I thinks it looks better. What do you think?  If it is ok, i will push it

**Comment by cesswairimu** [comment]
lovely! @asaayushisingh, yeah kindly push. Thanks a bunch

**Comment by asaayushisingh** [comment]
> lovely! @asaayushisingh, yeah kindly push. Thanks a bunch

Hey! @cesswairimu 😄  Kindly review the changes. Thank you!

**Comment by asaayushisingh** [comment]
Hey! @cesswairimu 😄 Kindly review the changes. Thank you!

**Comment by asaayushisingh** [comment]
Hey! @cesswairimu 😄 Kindly review the changes. Thank you!

**Comment by asaayushisingh** [comment]
Hey! @cesswairimu 😄 Kindly review the changes. Thank you!

**Comment by asaayushisingh** [comment]
Hey! @cesswairimu 😄 Kindly review the changes. Thank you!

**Review by cesswairimu — APPROVED** [review]
:tada: :tada: thanks again @asaayushisingh

**Pull request merged**
