### PR TITLE
update syntax of active record query(license method)

### LINKED ISSUE #437: update syntax of active record query to more recent style (license method)
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/controllers/feeds_controller.rb](https://github.com/publiclab/mapknitter/blob/main/app/controllers/feeds_controller.rb) in the `mapknitter` repository (press the little pen Icon) and edit the line as shown below. 

To get help installing the application on your computer, see [the project README](https://github.com/publiclab/mapknitter/tree/main/README.md) and get help at #307 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -18,8 +18,13 @@ def clean
   end
 
   def license
-    @maps = Map.find(:all,:order => "id DESC",:limit => 20, :conditions => {:archived => false, :password => '', :license => params[:id]},:joins => :warpables, :group => "maps.id")
-    render :layout => false, :template => "feeds/license"
+    @maps = Map.order(id: :desc)
+      .limit(20)
+      .where(archived: false, password: '', license: params[:id])
+      .joins(:warpables)
+      .group("maps.id")
+    render layout: false, template: "feeds/license"
     response.headers["Content-Type"] = "application/xml; charset=utf-8"
   end
 
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by ananya**
Fixes #437 

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code has been rebased on top of latest master (check if another pull request was added recently, and please rebase)
* [x] pull request is descriptively named and, if possible, multiple commits squashed if they're smaller changes

Thanks!

### CODE REVIEW

**Comment by gauravano** [comment]
**Some suggestions:** 
1. Prefer to work on separate feature-branch for each issue as it will help you in keeping your `main` branch clean. 
2. Including `Fixes #[issue-number]` in PR's first comment is good practice as it automatically close the tagged issue when PR gets merged.

Thanks!

**Comment by gauravano** [comment]
Also, dropping a screenshot here just to show that it's working normally 
Screenshot from 2019-03-24 01-17-29

Thanks!

**Comment by gauravano** [comment]
Merged :tada: :balloon:

**Comment by ananya** [comment]
@gauravano thank you for merging the pr :smiley: . Also can we change the pr template itself to have Fixes #[issue number] rather then References #[issue number] ?

**Comment by gauravano** [comment]
@ananya actually, I was thinking about that as many contributors are missing that part. You are welcome to raise PR for that. And, you can refer some more point to add from https://github.com/publiclab/plots2/blob/master/.github/PULL_REQUEST_TEMPLATE.md

Thanks!

**Comment by ananya** [comment]
@gauravano sure I will make the pr for the same :smiley:

**Pull request merged**
