### PR TITLE
Roll back to using Debian 9 with custom built GDAL

### PR DESCRIPTION
**Pull request by icarito**
Here I've rolled back the upgrade to Debian 10 / Buster because the Mysql Gem was having issues with libmariadb-dev. I had to backport Debian 10 packages of GDAL 2.4 but it seems to work much faster now!

Also this PR contains tweaks that are needed for building `unstable` branch as staging for the team to use for testing.

[//]: # (To mark checkboxe write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by icarito** [comment]
Hi @publiclab/reviewers this brings us back to Debian 9 with custom made packages of GDAL. 
This also makes it so that `unstable` branch will work automatically. The stable branch will depend on merging #462.

**Comment by jywarren** [comment]
OK!!!

**Comment by jywarren** [comment]
Uh oh, this seems to have errored in Travis -- https://travis-ci.org/publiclab/mapknitter/builds/516390419?utm_medium=notification&utm_source=email

**Comment by icarito** [comment]
This is because the repository GnuPG public key was uploaded yesterday
to the keyserver pool and not all mirrors seem to have propagated it.
Please retry the build - I'll figure out how long it should take or if
there's some other keyserver we can use!

**Pull request merged**
