### PR TITLE
Setup auto-comment on dependabot PRs

### PR DESCRIPTION
**Pull request by PeculiarE**
Follow up to #1734

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/mapknitter-reviewers` for help, in a comment below

### CODE REVIEW

**Comment by PeculiarE** [comment]
Hi @jywarren....I believe this should work for our purpose. Fingers crossed that it actually does 🤞

**Review by jywarren — APPROVED** [review]
OK  let's try!!

**Comment by jywarren** [comment]
OK, maybe there was still an error? I see https://github.com/publiclab/mapknitter/pull/1740 which was created just after we merged this!

**Comment by jywarren** [comment]
```
Error: TypeError: Cannot read property 'number' of undefined
Error: Cannot read property 'number' of undefined
```

Same error with "number" as i documented... i hope the action author writes back!!

**Comment by PeculiarE** [comment]
it is working actually, see this PR #1741  opened roughly 10mins after the merge. The comment is made as desired.

I dunno if you saw my comment over at #1734, but I did mention that I decided to no longer use that author's bot. In this PR, I created our own workflow to make the comment using the Github API and Github Actions. Full details [here](https://github.com/publiclab/mapknitter/pull/1734#issuecomment-1140147943).

**Comment by PeculiarE** [comment]
I'm assuming the merge had not yet fully happened before #1740 was opened. Because I'm looking at the workflow/checks in its thread now and it's running the old workflow that uses that author's bot (Label Actions / Process Label Action) and that's why it threw the 'number' error.

The next PR opened at #1741 contains the new workflow I created: 'Dependabot PR Auto-Comment task'  and this workflow does the job 😄

**Pull request merged**
