### PR TITLE
Update README.md

### LINKED ISSUE #687: Add first-timers-only-friendly badge to README
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/mapknitter/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

We want to add a new badge to the README file:

[first-timers-only-friendly](https://code.publiclab.org#r=all)

## Solution

At the top of the README, where you'll find other badges, lets add the following line:

```
[![first-timers-only-friendly](http://img.shields.io/badge/first--timers--only-friendly-blue.svg?style=flat-square)](https://code.publiclab.org#r=all)
```

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo [README instructions](https://github.com/publiclab/mapknitter/blob/main/README.md)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, an additional checklist will be provided for getting it merged

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

### PR DESCRIPTION
**Pull request by Hasan-Ali**
added a "first-timers-only" batch as requested, i am a beginner so if you have any feedback, let me know

Fixes #687 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@Hasan-Ali this is not quite right as you deleted the other badges now and the merge conflict is still there! Did you follow the steps above I gave you?

**Comment by Hasan-Ali** [comment]
@sashadev-sky I tried following the steps above, but when I get to the "rebase" point I get error as you predicted, problem is that i cant identify the conflicts in order to fix them

**Comment by sashadev-sky** [comment]
hmm thats something you'll want to learn how to do! rebasing comes up pretty often. What code editor do you use? VScode makes it very easy for me.

@gauravano any input here? <-- he knows all of the tricks

**Comment by Hasan-Ali** [comment]
@sashadev-sky  ok i think i resolved the conflicts and rebased everything, now what?

**Comment by gauravano** [comment]
GitHub's web editor is also good. I use that in case of minor conflicts. You can also try that - just click on Resolve conflict button and make changes. 

Or, follow https://github.com/publiclab/mapknitter/pull/694#pullrequestreview-253759160

**Comment by Hasan-Ali** [comment]
> GitHub's web editor is also good. I use that in case of minor conflicts. You can also try that - just click on Resolve conflict button and make changes.
> 
> Or, follow [#694 (review)](https://github.com/publiclab/mapknitter/pull/694#pullrequestreview-253759160)

thanks

**Comment by Hasan-Ali** [comment]
@gauravano thanks for the tip, I have a question, can I view these conflicts on visual studio code ? if so, can u point me to the way

**Comment by Hasan-Ali** [comment]
@sashadev-sky I want to retry the rebase, thanks for your help it is appreciated

**Comment by gauravano** [comment]
Hey @Hasan-Alsulaiman, I think you can. I use RubyMine and it shows merge conflicts and also give me option whether to override the old code, etc. I think VSCode also shows it. 

Just open your project directory with VSCode and if your branch has conflicts then just browse to the conflicting files and it will show the options too.

**Comment by gauravano** [comment]
have you opened new PR?

**Comment by sashadev-sky** [comment]
@Hasan-Alsulaiman no problem! I checked my VSCode and I believe the Git extension that allows this is this one: https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens

It has over 21 million downloads so I guess a lot of people are finding very useful

If you're still working here we can reopen this or I believe you can too!

**Pull request closed without merging**
