### PR TITLE
Font awesome update 2

### PR DESCRIPTION
**Pull request by rarrunategu1**
Fixes #715  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/mapknitter-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by rarrunategu1** [comment]
Still have a few places to update the icons at

**Comment by rarrunategu1** [comment]
script functions not working with the icons.  Looking into it.  Loading a video should return an error with a fa-times-circle in red but it doesn't.  It just continues to load
image

**Comment by jywarren** [comment]
Thanks @rarrunategu1 -- is there an error in the console when you try to upload a video?

I'll be circling around again to a bunch of open PRs next week after publishing MapKnitter to the live site (finally, hopefully today). So feel free to label any with `ready` if you want to get them closed out, i'll look out for that! Thanks!

**Comment by rarrunategu1** [comment]
There isn't an error in the console but now I am receiving the word error next to it but the icon doesn't activate from the event.  I feel it has to do with the new font awesome.  I'm going to look into the node_modules for it.

**Comment by rarrunategu1** [comment]
Actually, @jywarren this is a bug that is on mapknitter.org as well.  There are two sections that these javascript functions should work and change a green check in a circle to a red x in a circle if there is a an error.  I believe that's what it should do according to the code here.
https://github.com/publiclab/mapknitter/search?q=fa-times-circle&unscoped_q=fa-times-circle
Or does this go to something else?  If that's the case I an open another case to correct the script there.  Or do you prefer that it be combined with this pull request for installing the font awesome update?

**Comment by jywarren** [comment]
Let's try to solve them separately - thanks for catching it!
Maybe @divyabaid16 knows more about this particular UI?

**Comment by rarrunategu1** [comment]
@jywarren this is ready.  I checked all the files in which I removed the font awesome link src from and verified if the icons were working.  They are.  The only issue is the script which is a bug that was already there.  I'll open another issue for that.  Please review and merge.

**Comment by jywarren** [comment]
Awesome, great work! Thanks for being so thorough!!!

**Pull request merged**
