### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by jywarren**
A lot of code cleanup, plus a set of new tests.

### CODE REVIEW

**Comment by jywarren** [comment]
OK, i believe this should resolve the errors. Fingers 🤞 !

**Comment by jywarren** [comment]
OK, i believe this should resolve the errors. Fingers 🤞 !

**Comment by jywarren** [comment]
Hmm, 

```
Error: test_should_get_tag_feed(FeedsControllerTest): ActionView::Template::Error: undefined method `rfc822' for nil:NilClass
app/views/feeds/tag.builder:15:in `block (4 levels) in 

```

**Comment by jywarren** [comment]
Not sure what's up here. It works locally. Trying again...

**Comment by jywarren** [comment]
Interesting, i caught it with a unit test. Quite odd! locally i've added a test to just output all the maps associated with the tag `nice`, so i'll push that up to see what Travis gives us. 


```
Failure: <nil> expected to not be nil.
test_basics(TagTest)
test/unit/tag_test.rb:13:in `block in <class:TagTest>'
```

**Comment by jywarren** [comment]
Hmm! Oddly just that one field is nil:

```
Failure:
  <[]> expected but was
  <[#<Map id: 1, name: "Saugus Landfill Incinerator", lat: #<BigDecimal:55b8f520e618,'0.4243823313 02E2',27(27)>, lon: #<BigDecimal:55b8f520e550,'-0.7098491907 12E2',27(27)>, version: 1, password: "", styles: nil, created_at: nil, updated_at: "2019-01-30 01:07:32", description: "A landfill in Saugus, MA.", author: "anonymous", zoom: #<BigDecimal:55b8f520e398,'0.2E1',9(27)>, location: "", static_data: "", vectors: false, tiles: "google", email: "", archived: false, tile_url: nil, tile_layer: nil, license: "publicdomain", user_id: 1, anon_annotatable: false, slug: "saugus-landfill-incinerator">]>.
```

**Comment by jywarren** [comment]
Maybe we have to instantiate the fixture differently... Maybe the format is wrong in /test/fixtures/maps.yml

**Comment by jywarren** [comment]
Ok I'm hopeful this is it. I realized the tests were in a string format that maybe had a MySQL/sqlite incompatibility.

**Comment by jywarren** [comment]
:-)))

**Comment by gauravano** [comment]
Awesome work @jywarren :smile: :tada:

**Pull request merged**
