### PR TITLE
Merge latest changes from main into unstable

### PR DESCRIPTION
**Pull request by PeculiarE**
* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/mapknitter-reviewers` for help, in a comment below

### CODE REVIEW

**Comment by PeculiarE** [comment]
Hi @jywarren, does the drop and pick interactive rebase we talked about in https://github.com/publiclab/mapknitter/pull/1762#issuecomment-1163853841 come into play here as well? Or is this a different situation?

**Comment by PeculiarE** [comment]
Uh-oh, I dunno what went wrong. I pushed, and this PR got merged automatically (I have no idea why). But even more surprisingly is the message on the branch. That looks so strange 😓 

Screenshot 2022-07-06 at 12 13 42

**Comment by jywarren** [comment]
It's ok, it just closes when it sees those commits merge. But, did you do
-f? It's supposed to force push it and have no divergence from main. Odd. I
manually triggered the build though since it didn't seem to auto trigger.
Let's see what happens.

**Comment by PeculiarE** [comment]
Yeah, I saw that you manually started the build. And no, I didn't do -f when pushing. Is there a way to fix the divergence?

**Comment by jywarren** [comment]
Yes if you use -f when you push, it'll overwrite any differences!

**Comment by PeculiarE** [comment]
But there's no new change to push right now. Does this mean we're stuck with this divergence between both branches?

**Comment by jywarren** [comment]
No you can do the force push even without new commits and it will force it
to match the pushed branch without divergence.

**Comment by jywarren** [comment]
And look, it built!!  https://unstable.mapknitter.org/ ✨✨

**Comment by jywarren** [comment]
Hmm is your own main branch in sync with the publiclab main branch? I can look at this later today!

**Comment by PeculiarE** [comment]
Yes, it's in sync. Alright, thank you.

**Comment by jywarren** [comment]
OK, i can see it's in sync - both have the hash 000bb55, but unstable has f5a0758 -- yet it's supposed to be the same commit. So I think it's for some reason merged a rebased version of the last 84 commits; that means it should be identical, but since they were rebased, they are technically (according to git) unique and different commits, even if the content is the same. I'll see what's up with the -f option, that should work. Worst case we can add a new commit maybe?

**Comment by jywarren** [comment]
OK, i was able to push with 

```
gitpod /workspace/mapknitter (main) $ git push -f origin HEAD:unstable
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
remote: 
remote: GitHub found 40 vulnerabilities on publiclab/mapknitter's default branch (3 critical, 17 high, 15 moderate, 5 low). To find out more, visit:
remote:      https://github.com/publiclab/mapknitter/security/dependabot
remote: 
To https://github.com/publiclab/mapknitter.git
 + f5a0758a...000bb55d HEAD -> unstable (forced update)
```
I'll trigger a rebuild again now too.

**Comment by PeculiarE** [comment]
I wonder why the build is not being auto-triggered though....

**Comment by PeculiarE** [comment]
Thanks @jywarren....I have reached out to him. Awaiting his response 😊

**Comment by PeculiarE** [comment]
On that note, I was looking through all other builds on the Jenkins page, and I noticed that the stable build for MapKnitter is always manually triggered by you (for builds from May 19 till now). Could this also be related to the certificate issue?

**Comment by jywarren** [comment]
Hmm, maybe the triggering has been not working for a while? It looked
configured to trigger automatically though.

**Comment by PeculiarE** [comment]
> Hmm, maybe the triggering has been not working for a while?

Yup, very likely. Will ask Sebastian as well.

**Pull request merged**
