### PR TITLE
Add margin to sidebar content

### LINKED ISSUE #673: Add margin to sidebar content
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [x] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [x] 📝 **Update** 

Selection_169

The sidebar content overlaps the sidebar header. It can be seen as the border coming in between the contents of the header.

Add margin-top to the sidebar contents to solve the problem. 

https://github.com/publiclab/mapknitter/blob/03deef103df0d76a84c6de1a3c73e9712fd6f539/app/assets/stylesheets/maps.css.scss#L115

```
margin-top: 15px;
```
- [x] 💾 **Commit** your changes

- [x] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [x] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by theghostyced**
Fixes #673

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

Screenshot

**Before**
screenshot

**After**
Screenshot 2019-06-08 at 12 58 39 PM

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by theghostyced** [comment]
> Great work @theghostyced 🎉
> Could you please attach the screenshot for the same?
> 
> Thanks!

Alright am on it @divyabaid16

**Comment by theghostyced** [comment]
> > Great work @theghostyced 🎉
> > Could you please attach the screenshot for the same?
> > Thanks!
> 
> Alright am on it @divyabaid16

Screenshot has been added @divyabaid16

**Comment by divyabaid16** [comment]
Hi @theghostyced I guess you forgot to add the screenshot after the change has been made.

**Comment by theghostyced** [comment]
Hi @divyabaid16 Concerning showing the UI update, I wasn't able to fully setup the mapknitter application. I tried using another system to try and see if it was from my end but to no avail.

**Comment by theghostyced** [comment]
> Hi @theghostyced I guess you forgot to add the screenshot after the change has been made.

Hi @divyabaid16, Does the application have an admin? I can't seem to find the create a maps page to view the UI update

**Comment by divyabaid16** [comment]
@theghostyced you can just create a map anonymously to check the UI for the create a new map page.

Thanks!

**Comment by theghostyced** [comment]
Hi @divyabaid16. The after image has been added

**Comment by divyabaid16** [comment]
Hi @theghostyced I guess I did a small mistake from my side. 
Could you please delete  ```margin-top```  from where you have added and add it after line 161
https://github.com/publiclab/mapknitter/blob/03deef103df0d76a84c6de1a3c73e9712fd6f539/app/assets/stylesheets/maps.css.scss#L159

**Comment by theghostyced** [comment]
The changes have been made @divyabaid16

**Comment by divyabaid16** [comment]
@jywarren this is ready to be merged.
Here is how it looks.
Selection_171

Thanks!

**Comment by jywarren** [comment]
Perfect, thanks a lot!!!

**Comment by theghostyced** [comment]
twitter - @theghostyced

**Pull request merged**
