### PR TITLE
Singularization Issue Fixed

### LINKED ISSUE #636: Fix singularization case for "images"
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/mapknitter/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

On [mapknitter.org](https://mapknitter.org) the number of images used to created a map is listed for each post, but if you come across a map with only 1 image you can see that "images" is not singularized here is as it should be:

Screen Shot 2019-05-26 at 7 48 49 PM

## Solution

Let's fix this so the output for 1 image looks like this:

Screen Shot 2019-05-26 at 7 47 43 PM

Update this line from this: https://github.com/publiclab/mapknitter/blob/dc96adae1b376e7a90a3410c535dd547230caf5e/app/views/maps/_list.html.erb#L26

to this:

```Ruby
<%= map.warpables.length %> <%= map.warpables.length == 1 ? "images".singularize : "images" %> | <%= map.comments.length %> comments
```

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo [README instructions](https://github.com/publiclab/mapknitter/blob/main/README.md)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, an additional checklist will be provided for getting it merged

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

### PR DESCRIPTION
**Pull request by PoseidonSigmaX**
Fixes #636  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by divyabaid16** [comment]
@sashadev-sky for further review.
Thanks!

**Comment by gauravano** [comment]
Nice work @PoseidonSigmaX :tada:. Hey @sashadev-sky, I don't have merging rights in Mapknitter so let's wait for @jywarren. Thanks!

**Comment by PoseidonSigmaX** [comment]
Thanks @gauravano @sashadev-sky @divyabaid16  :)

**Comment by jywarren** [comment]
Super! And I'll give merge rights to @gauravano -- and if we get enough reviewers in the new mapknitter-reviewers group, and agree on a "policy" (like 2+ approving reviews?) then we can expand the maintainers group too. 🎉 

https://github.com/publiclab/mapknitter/issues/634

**Comment by sashadev-sky** [comment]
@jywarren can I have merge rights on this repo as well?

**Comment by jywarren** [comment]
Yes, however please follow the above "draft policy" of getting reviews, as we should do our best to establish some good working practices with so much work going on in parallel. Thanks!

**Comment by gauravano** [comment]
Thanks for giving merge rights @jywarren. I will be careful :+1:

**Pull request merged**
