### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by Himanshu40**
Just a space for identifying syntax

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code has been rebased on top of latest master (check if another pull request was added recently, and please rebase)
* [x] pull request is descriptively named and, if possible, multiple commits squashed if they're smaller changes

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Thank you very much! We're waiting on another fix before tests will start running properly again, but will pull in your fix when that's done! 

We'd love your help with another project if youre  interested!

https://publiclab.github.io/community-toolbox/#r=all

**Comment by Himanshu40** [comment]
Yeah I will look into it and wait for another fix and then I will pull it when this fix is done :+1:

**Comment by jywarren** [comment]
OK, re-running now!

**Comment by jywarren** [comment]
Hooray! Thanks a lot!

**Comment by Himanshu40** [comment]
You are welcome and in future, I want to do more @jywarren

**Pull request merged**
