### PR TITLE
Add "use current location" button to new map page

### LINKED ISSUE #1036: Add "use current location" button to new map page
We currently show a lat/lon and location search here:

https://mapknitter.org/maps/new

However, it could be useful to add a button to geolocate yourself, as we do on the front page, and to use that location 

We could use a button in the same input group, attached to the right side of the input field for location, with the icon `crosshairs` - https://fontawesome.com/v4.7.0/icon/crosshairs

image

This would take the following code: (see the final "div" for the new button)

```html
<div class="input-group">
      <div class="input-group-prepend"><button class="btn btn-outline-secondary" type="button"><i class="fa fa-search"></i></button></div>
      <input class="form-control ui-autocomplete-input" tabindex="2" type="text" value="" name="map[location]" id="map_location" autocomplete="off">
    <div class="input-group-append"><button class="btn btn-outline-secondary btn-geocode-map" type="button"><i class="fa fa-crosshairs"></i></button></div>
</div>
```

It'd go here:

https://github.com/publiclab/mapknitter/blob/684338a3f8a2fcd26107438e11224d20fbb37a5a/app/views/maps/new.html.erb#L34-L38

The next step is a little harder. We'll have to attach a `$('.btn-geocode-map').click()` handler and in `.click(function() { ... })` we'll have to handle the returned location and splice them into the latitude/longitude fields on the form. 

We can use the `map.locate()` method in Leaflet, like we do on the front page:

https://github.com/publiclab/mapknitter/blob/fc4a042b7c53c2eac94aa37225eca364cdcc4bf7/app/views/front_ui/index.html.erb#L234-L267

We'd love help with this!

### PR DESCRIPTION
**Pull request by blurry-x-face**
Fixes #1036 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/mapknitter-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Screenshot from 2019-10-14 01-40-33
Thanks!

### CODE REVIEW

**Comment by blurry-x-face** [comment]
@publiclab/mapknitter-reviewers @jywarren  please review this, I am having trouble with showing the current location on the map some help would be really appreciated as I am working for the first time on this project so I am a little clueless as to what to do next so any help would be appreciated.

**Comment by blurry-x-face** [comment]
Now it also zooms in I just had to add flyTo method.
Screenshot from 2019-10-14 12-23-41

**Comment by cesswairimu** [comment]
Wow this looks really great :tada: @publiclab/mapknitter-reviewers someone with more context of the issue please review. Thanks @blurry-x-face :100:

**Comment by cesswairimu** [comment]
Hey @blurry-x-face,  we have the prompt on the front page that gets current location the file is https://github.com/publiclab/mapknitter/blob/main/app/views/front_ui/index.html.erb...You can take a look and I can check the exact code that gets current location if it doesn't make sense...Thanks for working on this

**Comment by jywarren** [comment]
I'm so sorry for the slow response, this looks really awesome. Thanks @blurry-x-face !!!!

**Comment by jywarren** [comment]
Restarting tests to try to get the final ones to trigger!

**Comment by jywarren** [comment]
Awesome. Thanks a lot!!!!!

**Comment by blurry-x-face** [comment]
Thanks @jywarren :smile:

**Pull request merged**
