### PR TITLE
image display fix for #742 #780

### LINKED ISSUE #742: Multiple map images will not display.  Only one image at a time.
### What happened just before the problem occurred
testing a map upload and realized it didn't have deletion menu which is mentioned on issue #741 , but when I drag and drop it had that option but the picture did not seem to save but it did.  Once I deleted the first image the drag and drop image showed up but not the other ones.  This image however no longer had the pop up menu option to delete

### Relevant URLs

http://localhost:3000/maps/testmap

### PublicLab.org username

parker_rose

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

### LINKED ISSUE #780: Images are not showing up properly on the map
### What happened just before the problem occurred

When I created a map and was adding the images, only the first image that was added is shown in the map that too at the top left the corner. Other images though they are shown placed, after the refresh of the page they can't be seen.

### PR DESCRIPTION
**Pull request by jywarren**
fix #742 fix #780

Hooray! Thanks to @cesswairimu and @sashadev-sky -- v helpful!

### CODE REVIEW

**Comment by cesswairimu** [comment]
Exciting :rocket:

**Comment by kaustubh-nair** [comment]
Awesome!!

**Comment by jywarren** [comment]
```
 FAIL["test_should_output_json_format_methods", #<Minitest::Reporters::Suite:0x000000000388ad58 @name="WarpableTest">, 0.11620190299998967]
 test_should_output_json_format_methods#WarpableTest (0.12s)
        Expected: 18
          Actual: 19
        test/unit/warpable_test.rb:25:in `block in <class:WarpableTest>'
```

**Comment by jywarren** [comment]
Awesome!!!

**Pull request merged**
