### PR TITLE
Search by author name

### LINKED ISSUE #569: Improve search feature
### What happened just before the problem occurred
Add option to search image from author name.

### Relevant URLs

https://mapknitter.org

### PublicLab.org username
igniteeng000
(to help reproduce the issue)

### Browser, version, and operating system
chrome, ubuntu/windows

For bug reports, fill out the above template; for feature requests, you can delete the template.

### PR DESCRIPTION
**Pull request by igniteeng000**
Fixes #569  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

[//]: # (To mark checkbox write 'x' within the square brackets)

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by igniteeng000** [comment]
@publiclab/reviewers please review

**Comment by jywarren** [comment]
This codeclimate is really quite strict! Do you want to address any of it? 

Also, would you like to add a test here? 

Thank you so much!!!

**Comment by igniteeng000** [comment]
I will address codeclimate issues and test in another PR after my end semester exams i.e 8th May.

**Comment by igniteeng000** [comment]
@publiclab/reviewers @jywarren please review it again. I have fixed some codeclimate issues.

**Comment by jywarren** [comment]
Super!!!

**Pull request merged**
