### PR TITLE
Alert improvement and adding byebug gem

### LINKED ISSUE #367: Logout not working at MK
* Hi folks, are you able to logout from the MK. I tried but am not able to do so. @jywarren @gauravano
@jywarren when a user logs out from the plots2 should it be automatically logged out from the MK?

I was able to do so after refreshing the webpage.

### LINKED ISSUE #393: collapse login dropdown with map layers dropdown icon
### What happened just before the problem occurred

map1

### Relevant URLs

https://mapknitter.org/#4/47.95/-13.23

### PublicLab.org username
singhav
(to help reproduce the issue)

### Browser, version, and operating system
chrome ubuntu 18.04 LTS

For bug reports, fill out the above template; for feature requests, you can delete the template.

### PR DESCRIPTION
**Pull request by gauravano**
**Issues solved:** 
- [x] byebug gem added which helps in debugging
- [x] Currently, at production(mapknitter.org), success alerts are not shown, this problem is solved  
- [x] Added timestamp at redirect to solve Fixes #367 
- [x] Added z-index to render login dropdown above the leaflet-map icon Fixes #393
------
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code has been rebased on top of latest master (check if another pull request was added recently, and please rebase)
* [x] pull request is descriptively named and, if possible, multiple commits squashed if they're smaller changes

Thanks!

### CODE REVIEW

**Comment by gauravano** [comment]
Success alerts are visible now:

alerts_shown

**Comment by jywarren** [comment]
Feel free to merge this when you're ready! It looks great!

**Comment by gauravano** [comment]
@sashadev-sky can you try this PR on your system?

**Comment by sashadev-sky** [comment]
@gauravano yes will do that today! Sorry just saw this

**Comment by gauravano** [comment]
No issue @sashadev-sky!

**Comment by gauravano** [comment]
Actually, don't review it now Sasha. I am thinking of doing some more minor fixes in this PR only.

**Comment by sashadev-sky** [comment]
@gauravano @jywarren is there something wrong with my view because I see the original PR for the nav bar was not intended to look like this

**Comment by sashadev-sky** [comment]
@gauravano sorry I missed that message! But, I do think the things I wrote should be addressed regardlessly, doesn't have to be in this PR

**Comment by jywarren** [comment]
Oh hmm, maybe @stefannibrasil can look at this as she recently updated the navbar? Maybe there was a merge conflict or something? Thanks!

**Comment by stefannibrasil** [comment]
Hum, let me investigate this. It was not supposed to look like that at all. It looks like it's still using the old CSS configuration... Is it possible?

I'm not sure, I'll get back to you when I have something more concrete to say. 

About the display of the alerts, I think that if they are placed after the navbar, they should be shown correctly. There is a padding-bottom after the navbar, maybe the alert is being placed in the middle or something?

**Comment by stefannibrasil** [comment]
actually, I need some help to get the new changes from this repo. I tried using git fetch and git pull to get the changes after the new navbar was merged, but it does not update the commits. I wanted to test the 'main' branch with the updates. How do you all get the changes in your local machine? Thanks!

**Comment by jywarren** [comment]
Hmm, let me check. The PR was https://github.com/publiclab/mapknitter/pull/360... and it does appear in main branch commits: https://github.com/publiclab/mapknitter/commits/main

Are you in your local `main` branch or local `master` branch? We have changed the default to `main` some time ago so maybe that's causing you some issues?

**Comment by stefannibrasil** [comment]
I'm in the main but this might be something related to having the master in mind when I was installing the project. I'll try installing it again. Thanks, @jywarren

**Comment by stefannibrasil** [comment]
hi everyone, I was able to get the updates and test it locally :)

I added some notes on this PR #399 about the issue with the new navbar. Thanks, @sashadev-sky for pointing the problem with the navbar, Bootstrap 3 has this problem that wasn't aware. Please let me know if it's okay with the changes that I added there, but I think it should fix the problem.

**Comment by gauravano** [comment]
Hi everyone,

Thanks @sashadev-sky for the review and @stefannibrasil for the navbar fix. Sorry wasn't able to keep up with this PR. 

Rebasing my PR and doing some more fixes..

**Comment by gauravano** [comment]
@jywarren it's ready, please review it and merge it if you find all changes alright. Thanks!

**Comment by gauravano** [comment]
@jywarren please review it. Thanks!

**Comment by jywarren** [comment]
🎉 Thank you Gaurav!!!

**Pull request merged**
