### PR TITLE
Upgrade to bootstrap 4

### LINKED ISSUE #377: Update Bootstrap version to the latest version
The project is currently using Bootstrap 3.2.0, but it would be nice to update it to the newest version (now it`s at 4.3.1).

I'm finishing some tweaks on the navbar but as soon as it's finished I can start working on this one, but feel free to suggest anything or even start working on it :)

### PR DESCRIPTION
**Pull request by stefannibrasil**
Fixes  #377 

Hi all, I have some questions:

- Why do we have two `bower.json` files? I wasn't sure which one to use, so I updated both of them.
- In order to make Bootstrap 4 work, I had to install the `popper_js` gem and update `jquery-ui` version. 
- @icarito after I rebased my branch with some of your work from #450 the map on `/maps/some-map-title` wasn't working... It only worked after I re-added 3 dependencies that you had removed:
 ```
  # javascripts/application.js
  //= require leaflet-easybutton/src/easy-button.js
  //= require leaflet-google/index.js
  ```

and
```
  # javascripts/maps.js
  //= require seiyria-bootstrap-slider/dist/bootstrap-slider.min.js 
```

@icarito Did you manage to make the maps be shown without those 3 dependencies?

-----------

A little more about this PR: I just updated some of the components that were broken from switching to Bootstrap 4, especially because we will soon update the UI.

Please let me know if I did those version updates correctly, this was my first time doing something like this! :)
Appreciate any help here, I think I didn't forget anything here :shipit: 

@jywarren @gauravano @sashadev-sky (any more others I should mention here?)

### CODE REVIEW

**Comment by icarito** [comment]
Hi @Stefanni. Apologies for having removed those dependencies, it was an
oversight on my part! I thought I had restored them!

**Comment by icarito** [comment]
Actually I had tried this in order to set us up with a staging environment like we have for plots2 - in #429 and related issues we had a lot of moving around of dependency installation and I thought I'd put it all back, thanks for catching it!

I have here to share with you that our staging instances should be functional (currently we have an empty database but I'll copy database from production).

http://mapknitter-unstable.laboratoriopublico.org/  (built from _unstable branch_)
http://mapknitter-stable.laboratoriopublico.org/   (built from _main branch_)

@stefannibrasil @sashadev-sky @jywarren I hope it will be useful!

**Comment by sashadev-sky** [comment]
@icarito Thank you!!!

**Comment by stefannibrasil** [comment]
oh, don't worry, just wanted to double check, @icarito :)

that's awesome! I tried finding how to push to the staging branch, is it just run `git push stable`? Thanks!

**Comment by icarito** [comment]
I need to document it in the README - it builds on pushing to `main`
branch and Unstable builds on `unstable` branch.

While it works right now I'm still pending to copy data from production,
then I'll document it!

Thanks!

**Comment by jywarren** [comment]
I believe data was copied in over the weekend! @stefannibrasil did it work to push this up?

**Pull request closed without merging**
