### PR TITLE
Update LDI version

### PR DESCRIPTION
**Pull request by chen-robert**
Fixes part 2 of https://github.com/publiclab/Leaflet.DistortableImage/issues/367

I updated the LDI version in package.json with `yarn add leaflet-distortableimage` and refactored the code in `app/assets/javascripts/mapknitter/Map.js`. 

Could you please take a look @gauravano @SidharthBansal @sashadev-sky @IshaGupta18 @cesswairimu @divyabaid16 @jywarren? Thanks!

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@chen-robert I think you need to address #1124 or you will run into an error if you actually try to run the method! Code looks good though 👍

**Comment by chen-robert** [comment]
@sashadev-sky okay, I'll take a look at https://github.com/publiclab/mapknitter/issues/1124 now

**Comment by chen-robert** [comment]
I'm going to close and remake this branch to clean up the commits. Something went wrong regarding the LDI versioning in `package.json` and its easier to just start from master.

**Comment by sashadev-sky** [comment]
@chen-robert let me know if you need help making a rebase!! They're tough sometimess

**Comment by SidharthBansal** [comment]
Just checking, Chen you can't work on 2 prs as it is against gci rules.
Please resume this work after signup work. If anyone comes in the meantime and want to solve this. Then we have to give them a fair chance to solve.

**Pull request closed without merging**
